# questions_batch2.py: Questions 101 to 200
# Covers: ML, Isolation Forest, Mahalanobis Distance, Covariance, Features, Normalization

BATCH2_QUESTIONS = [
    (101, "What is Mahalanobis distance?",
     "Mahalanobis distance measures the distance between a multi-dimensional point x and a distribution mean mu, incorporating the covariance matrix Sigma to account for feature correlations and variances: D_M(x) = sqrt((x - mu)^T * Sigma^(-1) * (x - mu)).",
     "An elliptical ruler that measures how far a point is from the center, taking into account the natural tilt and spread of the data cloud.",
     "D_M(x) = sqrt((x - mu)^T * Sigma^{-1} * (x - mu)). Follows Chi-Square distribution with p degrees of freedom.",
     "backend/app/main.py: lines 2145-2160",
     "Memorize this matrix equation!"),

    (102, "Difference between Euclidean and Mahalanobis distance?",
     "Euclidean distance measures straight-line distance assuming features are orthogonal, uncorrelated, and have equal variance. Mahalanobis distance accounts for pairwise correlations and differing variances by scaling coordinates along principal eigenvectors.",
     "Euclidean draws circles; Mahalanobis draws ellipses that stretch to fit the data.",
     "Euclidean D_E = sqrt((x-mu)^T * (x-mu)). If Sigma = I (identity), Mahalanobis reduces to Euclidean.",
     "backend/app/main.py: lines 2145-2160",
     "Euclidean distance creates false alarms when features correlate."),

    (103, "What is covariance?",
     "Covariance measures the joint variability of two random variables: Cov(X, Y) = E[(X - E[X])(Y - E[Y])]. Positive covariance means when transfer amount increases, velocity also increases.",
     "A number that tells you if two features rise and fall together.",
     "Covariance matrix Sigma in R^{d x d} where Sigma_{ij} = Cov(X_i, X_j).",
     "backend/app/main.py",
     "Diagonal of covariance matrix equals feature variances."),

    (104, "Why invert the covariance matrix?",
     "Inverting the covariance matrix scales the coordinates inversely by their variance and rotates them to remove linear correlation, transforming the elliptical distribution into a standardized spherical space.",
     "It un-tilts the data cloud so you can measure true abnormality in all directions equally.",
     "Whitening transformation: transforms correlated X into uncorrelated Z with Cov(Z) = I.",
     "backend/app/main.py: lines 2150-2160",
     "Standardizes multi-feature scale differences."),

    (105, "Why use np.linalg.pinv()?",
     "We use Moore-Penrose pseudoinverse `np.linalg.pinv()` because if two forensic features are collinear or linearly dependent, the covariance matrix is singular (determinant zero) and standard inversion `np.linalg.inv` crashes with a LinAlgError.",
     "Standard inversion crashes if features overlap. The pseudoinverse safely handles zero eigenvalues using SVD.",
     "Computes generalized inverse Sigma^+ via SVD: Sigma = U * S * V^T, Sigma^+ = V * S^+ * U^T.",
     "backend/app/main.py: np.linalg.pinv(self.cov_matrix)",
     "Prevents production system crashes from collinear features."),

    (106, "What happens if covariance is singular?",
     "If covariance is singular, it means at least one feature is a linear combination of others or has zero variance. Standard matrix inversion fails with a division-by-zero error. `np.linalg.pinv()` solves this by inverting only non-zero singular values.",
     "Without pinv(), the entire server crashes with a LinAlgError.",
     "Rank of Sigma is less than dimension d; det(Sigma) = 0.",
     "backend/app/main.py",
     "Always explain pinv() as a production fault-tolerance control."),

    (107, "Is Mahalanobis part of Isolation Forest?",
     "NO. Mahalanobis distance is an independent statistical metric run in parallel with Isolation Forest. Isolation Forest partitions data via random orthogonal hyperplanes, while Mahalanobis measures parametric distance from the distribution centroid.",
     "They are two separate algorithms running side by side; we blend their scores together.",
     "Isolation Forest is tree-based non-parametric; Mahalanobis is centroid-based parametric.",
     "backend/app/main.py: lines 2145-2175",
     "TRAP: Never say Mahalanobis is an internal part of Isolation Forest!"),

    (108, "Why combine Isolation Forest and Mahalanobis?",
     "To provide defense-in-depth: Isolation Forest excels at capturing complex non-linear boundary partitions across multiple features, while Mahalanobis distance excels at detecting points that break linear correlation patterns.",
     "If an anomaly slips past the tree cuts, Mahalanobis catches it because it breaks the correlation angle.",
     "Composite anomaly score: S_comp = 0.6 * IF_Score + 0.4 * norm(Mahalanobis).",
     "backend/app/main.py: lines 2150-2175",
     "Hybrid non-parametric + parametric ensemble maximizes detection robustness."),

    (109, "How do you interpret a high Mahalanobis distance?",
     "A high Mahalanobis distance indicates that a transaction has an extreme, unexpected combination of features relative to normal correlation patterns (e.g. A huge transaction amount occurring with near-zero historical velocity).",
     "The point breaks the expected relationship rules of normal business.",
     "Sample falls beyond the 99.9th percentile Chi-Square critical threshold: D_M^2 > chi^2_{0.001, df=5}.",
     "backend/app/main.py",
     "Flagged as a high-priority advisory alert in the dashboard."),

    (110, "What features does your ML model use?",
     "Our model uses 5 engineered features: (1) Log Financial Amount; (2) Nocturnal Activity Ratio; (3) Kinematic Speed Velocity; (4) Degree Centrality; and (5) Rapid Fanout Rate.",
     "The 5 dimensions that represent how criminals move money, call each other, and travel.",
     "5D vector X in R^5 representing multi-modal transaction and behavior signals.",
     "backend/app/main.py: lines 2120-2135",
     "Know all 5 features by heart."),

    (111, "Why did you select these features?",
     "Because each feature directly captures a known criminal tradecraft evasion technique: log amount catches smurfing; nocturnal ratio catches covert communications; kinematic velocity catches courier convoys; degree centrality catches coordination hubs; and fanout rate catches money-dispersion tranches.",
     "They were picked because they reflect how organized crime syndicates actually operate.",
     "Domain-driven feature engineering aligned with criminological tradecraft.",
     "backend/app/main.py",
     "Shows strong domain knowledge in cyber-forensics."),

    (112, "What is financial velocity?",
     "Financial velocity is the rate of capital movement through an entity over time: Velocity = Total_Outflow / Delta_Time. In Hawala mules, velocity spikes abruptly upon receipt of dirty funds.",
     "How fast money leaves an account after arriving.",
     "First derivative of cumulative transaction volume with respect to time.",
     "backend/app/main.py: line 2125",
     "Mules have near-infinite velocity: money in is immediately money out."),

    (113, "What is nocturnal activity ratio?",
     "Nocturnal activity ratio is the proportion of communications executed between 02:00 and 05:00 AM: Ratio = Calls_0200_0500 / Total_Calls.",
     "The percentage of phone calls made in the dead of night.",
     "Temporal concentration ratio; normal business baseline < 0.05; criminal syndicates > 0.40.",
     "backend/app/main.py: line 2125",
     "Syndicates coordinate deliveries at night to avoid road police."),

    (114, "What is degree centrality as an ML feature?",
     "Degree centrality quantifies the node's direct network fanout: C_D(v) = (deg_in(v) + deg_out(v)) / (N - 1), capturing communication and transaction coordination intensity.",
     "How many people this person is directly talking to or paying.",
     "Normalized graph degree fed as a numerical column into the ML feature matrix.",
     "backend/app/main.py: line 2130",
     "Bridges graph theory into machine learning."),

    (115, "What is CDR burst z-score?",
     "CDR burst z-score measures how many standard deviations the current call frequency exceeds the suspect's 30-day baseline: Z = (Call_Count - Mean) / Std. Z > 3.5 denotes extreme burst chatter.",
     "A mathematical measure of sudden phone panic or intense operational coordination.",
     "Standardized normal deviation under Gaussian assumption.",
     "backend/app/main.py: lines 2120-2135",
     "Precedes major criminal events or follows police raids."),

    (116, "What is Benford deviation as an ML feature?",
     "Benford deviation is the Euclidean or Chi-Square distance between the suspect's transaction first-digit distribution and Benford's theoretical logarithmic curve: Dev = sqrt(sum (Obs_d - Exp_d)^2).",
     "A score showing how badly an account's transactions violate Benford's 30% first-digit rule.",
     "Goodness-of-fit residual metric fed into the ML vector.",
     "backend/app/main.py: lines 1230-1260",
     "Identifies fabricated invoice amounts."),

    (117, "How are features normalized?",
     "Features are normalized using Scikit-Learn's `RobustScaler`, which centers data by removing the median and scales according to the Interquartile Range (IQR = Q3 - Q1).",
     "We scale numbers using the middle 50% so giant outlier transactions don't break the math.",
     "x_scaled = (x - median(X)) / (Q75(X) - Q25(X)).",
     "backend/scripts/run_offline_benchmark.py: line 55",
     "RobustScaler is immune to extreme outlier distortion unlike StandardScaler."),

    (118, "Are the features correlated?",
     "Yes. Log financial amount and rapid fanout rate exhibit positive correlation (r ~ 0.68), which is precisely why we combine Isolation Forest with Mahalanobis distance to properly evaluate correlated covariance axes.",
     "Yes, people who move lots of money also move it fast. Mahalanobis distance accounts for this.",
     "Covariance matrix off-diagonal elements Sigma_{ij} != 0.",
     "backend/app/main.py: lines 2145-2160",
     "Uncorrelated assumptions fail on real financial data."),

    (119, "How do you handle missing values?",
     "Missing values are imputed using median imputation for continuous numerical features and explicit 0 for discrete counts, preventing distortion from non-normal distributions.",
     "If a phone has no calls recorded, we fill zero; if a transfer amount is blank, we use the median.",
     "SimpleImputer(strategy='median') applied inside the cross-validation pipeline.",
     "backend/scripts/run_offline_benchmark.py",
     "Never impute with mean when data has extreme outliers."),

    (120, "How do you handle extreme outliers during preprocessing?",
     "We do NOT clip or drop outliers during preprocessing because in forensic cyber-investigations, the outliers ARE the criminal signals! RobustScaler scales them without letting them distort the inlier centroid.",
     "We don't throw away extreme numbers because those extreme numbers are the criminals we are hunting!",
     "Outlier preservation is fundamental to anomaly detection.",
     "backend/scripts/run_offline_benchmark.py",
     "Dropping outliers in fraud detection throws away the ground truth!"),

    (121, "How do you prevent data leakage in feature engineering?",
     "By strictly fitting feature scalers (RobustScaler) only on training fold splits (`X_train`) during cross-validation, and applying `.transform()` to validation splits (`X_val`), ensuring test data never influences scaling parameters.",
     "Never let the test data peek at the training data's scaling rules.",
     "Strict pipeline isolation: fit on train, transform on val.",
     "backend/scripts/run_offline_benchmark.py: lines 50-70",
     "Fitting scalers on the whole dataset before splitting is a fatal data leakage error."),

    (122, "Why are these features meaningful forensically?",
     "They represent the operational realities of criminal syndicates: hiding money (smurfing), coordinating late at night (nocturnal), speeding between cities (kinematic velocity), talking to many couriers (degree), and rapidly dispersing cash (fanout).",
     "Every single feature corresponds to a real trick criminals use to avoid getting caught.",
     "Grounded in real-world criminological methodology.",
     "backend/app/main.py",
     "Shows you didn't just pick random columns."),

    (123, "Which feature is most important according to feature importance?",
     "Rapid Fanout Rate followed by Log Financial Amount: our tree split frequency analysis shows that smurfing volume and rapid dispersion account for over 52% of root and first-level partition cuts in Isolation Forest.",
     "Fast money dispersal and structured money amounts are the two biggest giveaways.",
     "Calculated by mean depth of first split on feature q across 200 trees.",
     "backend/app/main.py",
     "Aligns with financial crime realities."),

    (124, "How do you know your features are useful?",
     "By running ablation experiments: removing Rapid Fanout dropped validation F1 from 0.967 to 0.884; removing Nocturnal Ratio dropped F1 to 0.912. The full 5D feature set achieves maximal F1 (0.967).",
     "We tested removing features one by one and the score dropped every time, proving all 5 are necessary.",
     "Feature ablation study logged in benchmark validation suite.",
     "backend/data/ncfb_2026_cv_results.json",
     "Ablation studies are the gold standard for justifying features."),

    (125, "What is a Call Detail Record (CDR)?",
     "A CDR is a telecommunications transaction log produced by a telephone exchange, containing metadata for every call or SMS: caller MSISDN, receiver MSISDN, timestamp, duration, cell tower Cell ID (CGI), and first/last cell sector.",
     "The phone company's bill record: who called who, when, for how long, and which cell tower connected the call.",
     "Metadata record containing IMSI, IMEI, MSISDN, CGI, and session timestamps; does NOT contain voice audio recordings.",
     "backend/app/main.py",
     "CDRs contain metadata, not call audio transcripts!"),

    (126, "What information can a CDR contain?",
     "Caller number (A-party), receiver number (B-party), call timestamp, duration in seconds, call type (voice/SMS), Cell Global Identity (CGI) tower ID, Azimuth sector angle, and device IMEI/IMSI identifiers.",
     "Who called, who answered, what time, how many seconds, which tower, and which phone hardware was used.",
     "Standard 3GPP metadata schema.",
     "backend/app/main.py",
     "Under Indian law, telecom operators must retain CDRs for 2 years."),

    (127, "How do you analyze CDR patterns?",
     "By computing temporal call velocity, nocturnal ratios, degree centralities, co-location clusters across cell towers, and IMEI-SIM swapping patterns (when multiple burner SIMs share one handset).",
     "We look for people who call at 3 AM, people who switch SIM cards on the same phone, and phones that travel together.",
     "Graph link analysis + Temporal burst z-scoring + Geospatial co-location clustering.",
     "backend/app/main.py: lines 300-350",
     "Combines time, space, and identity."),

    (128, "What is call velocity?",
     "Call velocity is the number of outbound calls made by a phone number per unit of time (e.g., calls per hour). Sudden velocity spikes indicate crisis coordination.",
     "How many calls per hour a suspect makes.",
     "Rate of change: d(Calls) / dt.",
     "backend/app/main.py: line 2125",
     "Couriers have high call velocity during drop-offs."),

    (129, "What is a call burst?",
     "A call burst is a statistically significant surge in communication volume occurring within a short temporal window (e.g. 20 calls in 15 minutes) relative to quiet baselines.",
     "A sudden frenzy of calls happening right before or after a crime.",
     "Poisson burst process where event arrival rate lambda_burst >> lambda_baseline.",
     "backend/app/main.py",
     "Precedes major syndicate movements."),

    (130, "What is a z-score and what does a z-score of 3.5 mean?",
     "A z-score measures how many standard deviations a value is from the mean: Z = (X - mu) / sigma. A z-score of 3.5 means the call rate is 3.5 standard deviations above normal, representing an event that occurs by chance less than 0.02% of the time (p = 0.0002).",
     "It means this level of phone activity is 3.5 standard deviations above normal—an extreme, near-impossible coincidence.",
     "Z = (X - mu) / sigma. In normal distribution, P(Z > 3.5) = 0.00023.",
     "backend/app/main.py: lines 2120-2135",
     "Definitively flags a statistical burst."),

    (131, "Why analyze nocturnal activity?",
     "Legitimate commercial businesses operate during standard daylight hours. Criminal syndicates intentionally concentrate burner SIM chatter in late-night windows (02:00 to 05:00) to coordinate deliveries while law enforcement patrols are low.",
     "Normal people sleep at 3 AM; burner phones light up at 3 AM during drug or contraband drop-offs.",
     "Nocturnal Ratio = Calls_0200_0500 / Total_Calls. Baseline < 0.05; criminal syndicates > 0.40.",
     "backend/app/main.py: line 2125",
     "Night owls exist; nocturnal activity is one signal among five, never single proof of guilt."),

    (132, "Can nocturnal activity prove criminal behavior?",
     "NO. Shift workers, medical staff, software engineers, and gamers also make late-night calls. Nocturnal activity is an advisory feature that must be corroborated with financial smurfing and ANPR toll movements.",
     "Being awake at 3 AM doesn't make you a criminal; it is just one clue that must be backed by other evidence.",
     "Heuristic behavioral signal, not a legal element of crime.",
     "backend/app/main.py",
     "CRITICAL TRAP: Never claim calling at night proves someone is guilty!"),

    (133, "How do you handle legitimate night-time activity?",
     "By checking career metadata and baseline history: if an account consistently operates at night for 6 months (e.g. BPO call center worker), its nocturnal z-score is 0 (normal baseline). We only flag sudden deviations from individual baseline.",
     "If you work the night shift, that's your normal baseline so the system doesn't flag you. We only flag people whose nighttime calls suddenly spike.",
     "Personalized baseline z-scoring: Z_i = (X_i - mu_i) / sigma_i.",
     "backend/app/main.py",
     "Prevents mass false positives on shift workers."),

    (134, "What is trilateration?",
     "Trilateration is a mathematical technique for determining the position of an object by measuring its distances from three or more known reference points.",
     "Finding where a phone is by drawing 3 distance circles around 3 cell towers and seeing where they overlap.",
     "Solves system of non-linear sphere/circle equations: (x - x_i)^2 + (y - y_i)^2 = r_i^2.",
     "backend/app/main.py: lines 2975-3050",
     "Uses distances, NOT angles."),

    (135, "What is triangulation?",
     "Triangulation determines the position of a target by measuring angles from fixed reference stations using directional radio antennas.",
     "Finding location by measuring the compass angles from two lookout towers.",
     "Solves angle-side-angle trigonometry.",
     "backend/app/main.py",
     "Triangulation uses angles; trilateration uses distances."),

    (136, "Difference between triangulation and trilateration?",
     "Triangulation measures angles of arrival (AoA); trilateration measures distances using Time of Arrival (ToA) or Received Signal Strength (RSSI).",
     "Triangulation = Angles; Trilateration = Distances.",
     "Triangulation: uses directional antennas; Trilateration: uses omni-directional distance radiuses.",
     "backend/app/main.py: lines 2975-3050",
     "Classic telecommunications viva trap question!"),

    (137, "Why use three towers?",
     "Because in 2D space, two circles intersect at two ambiguous points. A third non-collinear circle resolves the ambiguity and uniquely determines the (x, y) coordinate.",
     "Two circles give two possible spots; the third circle tells you which spot is real.",
     "Two equations yield two solutions; three equations yield a unique over-determined solution.",
     "backend/app/main.py: lines 2980-3020",
     "In 3D (altitude), 4 towers are required."),

    (138, "How does distance estimation work?",
     "By measuring Received Signal Strength Indication (RSSI) and converting it to distance using an empirical radio path loss model (the Hata model).",
     "The weaker the cell phone signal, the further away the phone is from the tower.",
     "RSSI(d) = P_tx - PathLoss(d). Solves for distance d.",
     "backend/app/main.py: lines 2985-3010",
     "Signal fades logarithmically with distance."),

    (139, "What is the Hata model?",
     "The Hata model is an empirical radio propagation equation that predicts signal loss in urban environments based on frequency, antenna height, and distance: Pr(d) = Pt - 10*gamma*log10(d) + X_sigma.",
     "An empirical physics formula that calculates how much radio waves fade in a city with concrete buildings.",
     "Standard IEEE/ITU formula for urban cellular path loss.",
     "backend/app/main.py: lines 2985-3010",
     "Derived from extensive field measurements by Yoshihisa Okumura and Masaharu Hata."),

    (140, "What is path loss?",
     "Path loss is the reduction in power density (attenuation) of an electromagnetic wave as it propagates through space from transmitter to receiver.",
     "How much signal strength is lost as the radio wave travels through the air.",
     "PL(dB) = 10 * log10(P_tx / P_rx).",
     "backend/app/main.py",
     "Caused by free-space spreading, absorption, and reflection."),

    (141, "What does propagation exponent 2.8 mean?",
     "In vacuum, radio waves spread according to the inverse-square law (gamma = 2.0). In dense cities like Mumbai with concrete buildings, radio waves attenuate faster: gamma = 2.8 represents heavy urban path loss.",
     "Buildings absorb radio waves, so signals fade much faster than in open desert.",
     "gamma in [2.7, 3.5] for dense urban clutter.",
     "backend/app/main.py: gamma=2.8",
     "Using free-space gamma=2.0 in a city causes massive distance underestimation."),

    (142, "What is WLS (Weighted Least Squares)?",
     "Weighted Least Squares is an optimization algorithm that solves over-determined systems of equations by weighting each equation inversely by its measurement variance, giving higher weight to towers with stronger Signal-to-Noise Ratio (SNR).",
     "Trusting the close, loud cell tower more than the faint, crackly tower.",
     "delta_x = (J^T * W * J)^(-1) * J^T * W * delta_r, where W = diag(1 / sigma_i^2).",
     "backend/app/main.py: lines 3010-3045",
     "Outperforms unweighted least squares when signal qualities differ."),

    (143, "Why use Weighted Least Squares?",
     "Because cell tower signals have varying noise levels: a tower 500m away with direct line of sight has high SNR and low error, while a tower 3 km away has high multipath noise. WLS downweights noisy towers.",
     "It gives more votes to the reliable nearby tower and fewer votes to the noisy distant tower.",
     "Minimizes sum of weighted residuals: min sum w_i * (r_i - d_i(x))^2.",
     "backend/app/main.py",
     "Standard Least Squares treats all towers equally, degrading accuracy."),

    (144, "What is the WLS normal equation?",
     "delta_x = (J^T * W * J)^(-1) * J^T * W * delta_r, where J is the Jacobian matrix of partial derivatives of distances with respect to coordinates (x, y), W is the diagonal weight matrix, and delta_r is the distance residual vector.",
     "The mathematical formula that calculates the position update from the weighted tower measurements.",
     "Gauss-Newton iterative update for non-linear least squares.",
     "backend/app/main.py: lines 3015-3035",
     "Memorize this matrix equation for telecom questions!"),

    (145, "What is GDOP (Geometric Dilution of Precision)?",
     "GDOP is a dimensionless geometric multiplier that quantifies how the spatial geometry of reference cell towers amplifies ranging errors into final position error: sigma_pos = GDOP * sigma_range.",
     "A geometry score: if towers surround you like a tripod, GDOP is small (good). If towers are all in a line, GDOP is huge (bad).",
     "GDOP = sqrt(trace((J^T * J)^(-1))).",
     "backend/app/main.py: lines 3020-3040",
     "Derived entirely from tower geometry, not signal strength."),

    (146, "What is the GDOP formula?",
     "GDOP = sqrt(trace((J^T * J)^(-1))), where J is the unit-vector directional Jacobian matrix between the estimated target position and each cell tower.",
     "Square root of the trace of the inverse of J-transpose times J.",
     "Quantifies error covariance matrix diagonal sum.",
     "backend/app/main.py: line 3030",
     "Standard GPS and cellular navigation formula."),

    (147, "What does GDOP 1.14 mean?",
     "GDOP 1.14 indicates near-optimal geometric satellite/tower configuration: our three Mumbai towers (Goregaon, Bandra, Andheri) surround the target symmetrically, amplifying baseline ranging errors by only 14%.",
     "The towers form an almost perfect triangle around the suspect, giving great accuracy.",
     "GDOP 1.14 is close to ideal theoretical minimum (1.0).",
     "backend/app/main.py: line 3035",
     "GDOP < 2 is rated 'Excellent' in radio navigation."),

    (148, "Where does ±12.4m come from?",
     "By multiplying our Geometric Dilution of Precision (GDOP = 1.14) by our baseline simulated radio ranging standard deviation (sigma_range = 10.8m): sigma_pos = 1.14 * 10.8m = ±12.31m (~±12.4m).",
     "1.14 geometry factor multiplied by 10.8 meters ranging error gives ±12.4 meters uncertainty radius.",
     "sigma_pos = GDOP * sigma_range = 1.14 * 10.8 = ±12.31m.",
     "backend/app/main.py: line 3040",
     "TRAP: It is a theoretical simulated uncertainty radius, NOT an empirical field drive-test!"),

    (149, "Is ±12.4m real-world accuracy?",
     "NO. In real-world urban environments without GPS, cellular trilateration accuracy typically ranges from 150m to 500m due to Non-Line-of-Sight (NLOS) blocking and multipath fading. ±12.4m is a theoretical simulated covariance bound.",
     "No, in a real city with concrete buildings, cellular accuracy is 150 to 500 meters. ±12.4m is a theoretical math formula bound.",
     "Idealized line-of-sight Gaussian assumption; real cities suffer from severe NLOS multipath bias.",
     "backend/app/main.py",
     "CRITICAL TRAP: Never claim you measured ±12.4m on real city streets!"),

    (150, "What assumptions produce ±12.4m?",
     "Three assumptions: (1) Direct line-of-sight (LOS) radio propagation; (2) Zero multipath reflections; and (3) Gaussian zero-mean ranging noise with standard deviation sigma = 10.8m.",
     "Assumes no concrete buildings blocking the signal and pure textbook radio waves.",
     "Theoretical Cramér-Rao Lower Bound (CRLB) under Gaussian noise.",
     "backend/app/main.py",
     "Honesty about assumptions proves engineering maturity."),

    (151, "What happens in Non-Line-of-Sight (NLOS) conditions?",
     "Buildings block the direct radio path, forcing the wave to diffract over rooftops or reflect off distant walls. This extra distance introduces positive ranging bias, making distance estimates appear much larger and distorting coordinates.",
     "The radio wave takes a detour around a skyscraper, making the phone appear 300 meters further away than it is.",
     "Positive distance bias: r_measured = r_true + b_NLOS + noise, where b_NLOS > 0.",
     "backend/app/main.py",
     "The primary source of error in urban cellular positioning."),

    (152, "What happens because of multipath?",
     "The radio signal bounces off ground, vehicles, and buildings, arriving at the antenna via multiple paths with differing phase shifts, causing destructive interference (Rayleigh fading) and signal dropouts.",
     "Echoes of the radio signal clash with each other, causing the signal to flicker and fade.",
     "Rayleigh/Rician fast fading causing severe RSSI fluctuation.",
     "backend/app/main.py",
     "Makes RSSI distance estimation noisy."),

    (153, "How would you validate this in the real world?",
     "By conducting drive-test validation: driving an instrumented vehicle with high-precision RTK-GPS (cm-level ground truth) while logging cellular tower RSSIs, comparing WLS estimated coordinates against RTK-GPS coordinates to calculate true Root Mean Square Error (RMSE).",
     "Drive a test car with real GPS and an antenna around Mumbai, and compare the real GPS position against the estimated tower position.",
     "Empirical field drive-test benchmarking across urban, suburban, and rural clutter zones.",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Shows you understand how telecom operators actually calibrate networks."),

    (154, "What is a Kalman filter?",
     "A Kalman filter is an optimal recursive mathematical algorithm that estimates the true hidden state of a dynamic system from a series of incomplete and noisy measurements over time.",
     "A math formula that uses physics and past movement to guess where a moving vehicle is right now, filtering out sensor jitter.",
     "Linear Quadratic Estimator (LQE) minimizing mean squared error.",
     "backend/app/main.py: class KalmanFilter2D (lines 2780-2840)",
     "Used in Apollo moon missions, GPS navigation, and CrimeNet vehicle tracking."),

    (155, "Why use a Kalman filter in CrimeNet?",
     "To track suspect courier vehicles between highway toll cameras: ANPR cameras only take photos at discrete toll plazas. The Kalman filter estimates continuous vehicle position and velocity between cameras, smoothing out timestamp jitter.",
     "Highway cameras only snap a photo every 20 km. The Kalman filter predicts where the car is in between the cameras.",
     "Fuses kinematic motion model with intermittent ANPR camera detections.",
     "backend/app/main.py: lines 2780-2840",
     "Provides continuous trajectory tracking across highway corridors."),

    (156, "What is the state vector?",
     "The state vector x is a column vector containing the minimal set of variables needed to describe the dynamic physical state of the system at any given time step k.",
     "The list of numbers describing the car: its horizontal position, vertical position, horizontal speed, and vertical speed.",
     "x_k = [x, y, v_x, v_y]^T in R^4.",
     "backend/app/main.py: line 2785",
     "Contains both position and velocity."),

    (157, "Why use [x, y, vx, vy]^T?",
     "Tracking both position (x, y) and velocity (vx, vy) allows the filter to model momentum: a car traveling at 120 km/h cannot instantaneously stop or change direction, allowing the filter to reject impossible sensor teleportations.",
     "Because cars have momentum: knowing how fast they are driving tells you where they will be next minute.",
     "Constant Velocity (CV) kinematic motion model.",
     "backend/app/main.py: line 2785",
     "Position-only models cannot filter out timestamp jitter."),

    (158, "What is the prediction step in Kalman filtering?",
     "The prediction step uses physical motion equations to project the vehicle state forward in time: x_pred = F * x + B * u, and projects error covariance forward: P_pred = F * P * F^T + Q.",
     "Using physics (distance = speed * time) to guess where the car moved since the last camera photo.",
     "Time update equations.",
     "backend/app/main.py: lines 2795-2810",
     "Increases uncertainty (P_pred grows due to process noise Q)."),

    (159, "What is the update step in Kalman filtering?",
     "The update step incorporates a new camera measurement z_k: it calculates the Kalman Gain K = P_pred * H^T * (H * P_pred * H^T + R)^(-1) and updates the state estimate: x = x_pred + K * (z - H * x_pred).",
     "When a new camera snaps a photo, you compare reality to your guess and correct your position.",
     "Measurement update equations.",
     "backend/app/main.py: lines 2815-2835",
     "Reduces uncertainty (P shrinks after measurement update)."),

    (160, "What is measurement noise (R)?",
     "Measurement noise covariance matrix R represents the statistical uncertainty and error variance in the sensor readings (e.g. ANPR camera timestamp clock drift, GPS multipath jitter).",
     "How much you distrust the camera's GPS accuracy.",
     "R = diag(sigma_{x_meas}^2, sigma_{y_meas}^2).",
     "backend/app/main.py: line 2790",
     "High R means sensor is noisy; filter relies more on motion physics."),

    (161, "What is process noise (Q)?",
     "Process noise covariance matrix Q represents the uncertainty in the physical motion model (e.g. Suspect vehicle accelerating, braking, or changing lanes between toll gates).",
     "How unpredictably the driver can accelerate or turn between cameras.",
     "Q in R^{4 x 4}; models random acceleration disturbances.",
     "backend/app/main.py: line 2790",
     "High Q means vehicle drives erratically; filter relies more on camera measurements."),

    (162, "What is the Kalman gain (K)?",
     "The Kalman gain K is a weighting matrix that optimally balances model prediction against sensor measurement: K = P_pred * H^T * (H * P_pred * H^T + R)^(-1). K ranges between 0 (trust physics model entirely) and 1 (trust sensor measurement entirely).",
     "The blending dial: if the camera is crystal clear, turn the dial to camera; if the camera is blurry, turn the dial to physics.",
     "Optimal gain minimizing posterior error covariance.",
     "backend/app/main.py: line 2820",
     "Dynamically adjusts at every time step."),

    (163, "What happens if measurement noise increases?",
     "If measurement noise R approaches infinity, the Kalman gain K approaches zero (K -> 0). The filter ignores the noisy sensor measurements entirely and relies purely on its physical motion predictions.",
     "If the camera is broken and sending static, the filter ignores it and keeps driving the car using physics momentum.",
     "lim_{R -> inf} K = 0; state update x_k = x_pred.",
     "backend/app/main.py",
     "Prevents noisy sensors from throwing off vehicle tracking."),

    (164, "Where is Kalman filtering used in CrimeNet?",
     "In `backend/app/main.py`, lines 2780-2840, in the vehicle tracking pipeline to smooth vehicle trajectories between toll gates on the Mumbai-Pune Expressway and predict arrival times at downstream police checkpoints.",
     "On the highway map to track courier cars between toll plazas.",
     "KalmanFilter2D class used in ANPR tracking service.",
     "backend/app/main.py: lines 2780-2840",
     "Enables proactive police deployment at upcoming toll gates."),

    (165, "How do you detect suspicious transactions overall?",
     "By combining three complementary analytical layers: (1) Graph topology (Johnson's elementary cycles for circular laundering); (2) Unsupervised machine learning (Isolation Forest + Mahalanobis distance for smurfing velocity spikes); and (3) Benford Chi-Square analysis for accounting manipulation.",
     "We check if money moves in circles, if money moves too fast in small amounts, and if the digits look fake.",
     "Graph Theory + Tree Anomaly Detection + Benford Statistical Law.",
     "backend/app/main.py: lines 1150-1275",
     "Multi-layered detection eliminates single-point blind spots."),

    (166, "What is transaction velocity?",
     "Transaction velocity is the frequency or aggregate volume of fund transfers passing through an account per unit of time (e.g. transfers per hour). Mules exhibit extreme velocity surges.",
     "How fast money enters and leaves a bank account.",
     "d(Transfers) / dt.",
     "backend/app/main.py: line 2125",
     "Normal salary accounts have low velocity; Hawala mules have rapid velocity spikes."),

    (167, "What is rapid fan-out?",
     "Rapid fan-out occurs when an account receives a large lump-sum deposit and immediately disperses it across 5 to 20 sub-mule accounts within 60 minutes to frustrate tracking and asset freezes.",
     "A large deposit arrives and is immediately split into 10 smaller payments in minutes.",
     "Outbound fan-out degree derivative: d(Out_Degree) / dt.",
     "backend/app/main.py: line 2125",
     "Feature 5 in our Isolation Forest model."),

    (168, "What is Hawala structuring (smurfing)?",
     "Structuring is the deliberate practice of splitting large amounts of cash into multiple transactions below statutory reporting limits (e.g. ₹48,000 to avoid the ₹50,000 PAN requirement under Income Tax Rule 114B).",
     "Breaking a ₹5,00,000 deposit into 11 smaller payments under ₹50,000 to avoid police or tax scrutiny.",
     "Evades PMLA 2002 reporting thresholds.",
     "backend/app/main.py: lines 1150-1200",
     "Primary indicator of money laundering."),

    (169, "How do you detect transaction chains?",
     "By performing directed Breadth-First Search (BFS) bounded at 5 hops across the financial transaction subgraph, linking the source funder to the ultimate beneficiary through intermediary mule accounts.",
     "Following the money trail hop-by-hop from account A to B to C to D.",
     "Traces directed paths in G_financial where edge weights represent transfer amounts.",
     "backend/app/main.py: lines 450-510",
     "Uncovers layered proxy mule accounts."),

    (170, "How do you detect circular transactions?",
     "Using Donald B. Johnson's elementary cycles algorithm `nx.simple_cycles(G_financial)` to locate closed directed loops where funds circulate back to the originator.",
     "Finding loops where money leaves suspect A, passes through 3 mules, and ends up back with suspect A.",
     "Elementary cycles in directed financial graph.",
     "backend/app/main.py: lines 1150-1210",
     "Characteristic topology of Hawala laundering."),

    (171, "How do you identify unusual transaction amounts?",
     r"By computing feature 1: Log Financial Amount $\log_{10}(\text{Amount} + 1)$ and evaluating its Mahalanobis distance relative to historical account baselines, flagging transactions that exceed 3.5 standard deviations.",
     "Using math to spot transfers that are dramatically larger or structured differently than normal daily business.",
     "Standardized log-normal z-score evaluation.",
     "backend/app/main.py: lines 2120-2160",
     "Robust to heavy-tailed financial distributions."),

    (172, "Can your system prove financial crime in court?",
     "NO. CrimeNet AI generates probabilistic forensic intelligence and advisory alerts. Proving financial crime under the Prevention of Money Laundering Act (PMLA) 2002 requires certified bank account statements, tax filings, and evidence of scheduled predicate offenses.",
     "The software highlights red flags; it takes bank records, witness statements, and court testimony to convict someone.",
     "Advisory decision-support; criminal guilt requires judicial prosecution under PMLA.",
     "backend/app/main.py",
     "CRITICAL TRAP: Never claim software alone proves financial crime!"),

    (173, "How do you avoid false accusations against innocent people?",
     "Through three safeguards: (1) All detections are strictly Advisory Alerts; (2) Human-in-the-Loop review requires a verified officer badge signoff; (3) Explainable AI baselines show why the alert was generated, allowing officers to identify innocent explanations (e.g. medical emergency transfers).",
     "The AI never accuses anyone; it asks a human officer to inspect the file, showing clear reasons why.",
     "Responsible AI framework prevents autonomous legal action.",
     "backend/tests/test_responsible_ai.py",
     "Tested in `test_alerts_contain_advisory_status()`."),

    (174, "What is Benford's Law expected first-digit distribution?",
     "P(1) = 30.1%, P(2) = 17.6%, P(3) = 12.5%, P(4) = 9.7%, P(5) = 7.9%, P(6) = 6.7%, P(7) = 5.8%, P(8) = 5.1%, P(9) = 4.6%.",
     "Digit 1 happens 30% of the time, while digit 9 happens only 4.6% of the time.",
     "P(d) = log10(1 + 1/d) for d in {1..9}. Total sum = 100%.",
     "backend/app/main.py: lines 1225-1240",
     "Memorize 30.1% for 1 and 4.6% for 9!"),

    (175, "What is Chi-Square in Benford's Law?",
     "Pearson's Chi-Square goodness-of-fit test measures whether the observed distribution of first digits in a financial ledger differs significantly from Benford's theoretical logarithmic curve.",
     "A statistical test that calculates how far the account's numbers deviate from Benford's 30% curve.",
     "chi^2 = sum ((O - E)^2 / E) with degrees of freedom df = 8.",
     "backend/app/main.py: lines 1230-1255",
     "Standard test for categorical distribution fit."),

    (176, "Give the Chi-Square formula.",
     "chi^2 = sum_{d=1}^9 (O_d - E_d)^2 / E_d, where O_d is observed digit frequency and E_d is expected digit frequency (N * log10(1 + 1/d)).",
     "Sum of (Observed - Expected)^2 divided by Expected for digits 1 to 9.",
     "Degrees of freedom df = 9 - 1 = 8.",
     "backend/app/main.py: line 1245",
     "Memorize this formula!"),

    (177, "How do you calculate Benford deviation?",
     "We count leading digits of all transactions in an account, compute observed percentages O_d, calculate expected counts E_d, and evaluate Pearson's Chi-Square statistic against the critical threshold 15.51.",
     "Count how many 1s, 2s, 3s... appear as the first digit, and compare to Benford's percentages.",
     "Evaluated at alpha = 0.05 (critical chi2 = 15.51).",
     "backend/app/main.py: lines 1220-1260",
     "Computes chi2 and p-value."),

    (178, "What does a high Chi-Square value indicate?",
     "A high Chi-Square value (e.g. 41.22 >> 15.51) indicates that the probability of the ledger occurring naturally is less than 0.1% (p < 0.001), indicating strong statistical evidence of fabricated or manipulated transactions.",
     "It means there is a 99.9% chance someone made up these financial numbers by hand.",
     "Rejection of null hypothesis of natural accounting compliance.",
     "backend/app/main.py: line 1250",
     "Triggers high-priority forensic audit alert."),

    (179, "Does Benford prove fraud?",
     "NO. Benford's Law proves that numerical records do not follow natural first-digit distributions. It flags statistical manipulation, which can also happen in legitimate businesses with fixed prices (e.g. ₹99 subscriptions). Human review is mandatory.",
     "It proves the numbers look artificial, not that someone committed a crime. An investigator must verify the invoices.",
     "Statistical signal, not legal proof of fraud.",
     "backend/app/main.py",
     "Always emphasize that Benford is an analytical screener."),

    (180, "What are the limitations of Benford's Law?",
     "Benford's Law fails when: (1) Data has artificial minimum or maximum caps (e.g. sub-₹50k tranches); (2) Numbers are assigned sequentially (invoice numbers); (3) Dataset is too small (N < 500); or (4) Prices are psychologically fixed (e.g. ₹99, ₹199).",
     "Don't use it on small datasets, check numbers, phone numbers, or stores where everything costs ₹50.",
     "Requires at least 3 orders of magnitude and unconstrained data.",
     "backend/app/main.py: lines 1220-1240",
     "Know these 4 limitations."),

    (181, "When should Benford's Law NOT be used?",
     "When analyzing structured smurfing amounts: if criminals deliberately transfer ₹49,500 every time, the first digit will always be 4! Benford is designed for natural business ledgers, not single-amount smurfing.",
     "If a criminal transfers exactly ₹48,000 twenty times, all digits start with 4. Use cycle detection and velocity for that, not Benford.",
     "Single-valued repeated structuring violates Benford scale invariance.",
     "backend/app/main.py",
     "Use Isolation Forest and Johnson's cycles for structured smurfing."),

    (182, "Is NCFB-2026 an official benchmark?",
     "NO. NCFB-2026 is our synthetic CrimeNet AI forensic benchmark, generated for research and model evaluation in our project. It is NOT an official government or police dataset.",
     "No, it is our project's synthetic benchmark dataset, created to test our algorithms scientifically.",
     "Project research benchmark; generated with reproducible seed=42.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "CRITICAL TRAP: Never claim NCFB-2026 is a government-issued standard!"),

    (183, "How many records and anomalies are in NCFB-2026?",
     "10,000 total records: 9,520 normal transactions and 480 injected forensic anomalies (4.8% contamination).",
     "10,000 rows with 480 realistic criminal transactions.",
     "Shape: (10000, 7) including ID, 5 features, and ground-truth label.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Know these exact numbers."),

    (184, "Why 4.8% anomalies?",
     "Because in real financial and telecom systems, severe criminal operations represent 2% to 5% of total volume. 4.8% provides realistic class imbalance while ensuring 96 anomalies in each fold during 5-fold cross-validation.",
     "Matches realistic fraud rates in real banks and leaves enough test examples in each cross-validation fold.",
     "P(anomaly) = 0.048.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Balanced 50/50 datasets are unrealistic for fraud."),

    (185, "How was the synthetic data generated?",
     "Using `backend/scripts/generate_synthetic_benchmark.py`: inliers were generated from log-normal financial distributions and Poisson toll arrivals; anomalies were injected by simulating Hawala smurfing tranches (sub-₹50k), nocturnal call bursts, and high-speed highway transits.",
     "Using a Python script that simulated 9,520 normal citizens and 480 realistic criminal transactions with extreme features.",
     "NumPy multivariate distributions + injected rule-based criminal tradecraft signatures.",
     "backend/scripts/generate_synthetic_benchmark.py",
     "Fully reproducible via seed=42."),

    (186, "Why use synthetic data?",
     "Because distributing real citizen telecommunications intercepts or bank ledgers is strictly illegal under the DPDP Act 2023 and Indian Telegraph Act. Synthetic data allows rigorous, reproducible scientific benchmarking without violating citizen privacy.",
     "Because putting real citizen phone calls on GitHub is a crime. Synthetic data allows open scientific testing safely.",
     "Statutory privacy compliance (DPDP Act 2023).",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Respecting privacy laws shows professional maturity."),

    (187, "Why not real forensic data?",
     "Real forensic police evidence is classified under Official Secrets Act and judicial seals. Law enforcement agencies cannot publish raw citizen phone taps or bank statements in open repositories.",
     "Real police wiretaps are confidential government property and cannot be shared publicly.",
     "Legal restriction: Section 5(2) Indian Telegraph Act.",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Panels know real data cannot be shared; be honest."),

    (188, "What distributions did you use?",
     "Log-normal distribution for financial transaction amounts (mu=9.2, sigma=1.8), power-law degree distribution for social graph connectivity (gamma=2.4), and Poisson distribution for toll camera vehicle arrivals (lambda=4.2).",
     "Log-normal for money, power-law for social connections, and Poisson for highway cars.",
     "Empirical statistical distributions matching peer-reviewed financial criminological literature.",
     "backend/scripts/generate_synthetic_benchmark.py",
     "Matches real-world heavy-tailed patterns."),

    (189, "How did you inject anomalies?",
     "By modifying 480 specific rows: setting transfer amounts to sub-₹50k smurfing tranches, shifting call timestamps to 02:00-05:00 AM, inflating call burst z-scores above 3.5, and increasing vehicle transit speeds above 130 km/h.",
     "We edited 480 rows to give them the exact fingerprints of real criminals: 3 AM calls, fast driving, and rapid money splitting.",
     "Injected multi-feature outliers along known syndicate tradecraft vectors.",
     "backend/scripts/generate_synthetic_benchmark.py: lines 60-110",
     "Anomalies reflect real criminal modus operandi."),

    (190, "What makes an injected anomaly?",
     "An injected anomaly violates the joint distribution across multiple feature dimensions simultaneously (e.g. A high-value transfer occurring at 3:30 AM with an impossible transit speed).",
     "A transaction that is weird across multiple features at the exact same time.",
     "Multi-dimensional density outlier.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Single-feature outliers are easy; multi-feature anomalies test real ML capability."),

    (191, "How do you guarantee reproducibility?",
     "By fixing `random_state=42` and `np.random.seed(42)` across all generation, training, and cross-validation scripts, guaranteeing bit-for-bit identical results on any machine.",
     "By locking the random seed so another developer running the code gets the exact same 10,000 rows and 96.7% score.",
     "Deterministic pseudorandom sequence across Python and C-extensions.",
     "backend/scripts/run_offline_benchmark.py: line 20",
     "Essential for scientific validation."),

    (192, "Where is the dataset stored?",
     "In `backend/data/ncfb_2026_benchmark_10k.csv`, a 499 KB CSV file containing 10,001 lines (header + 10,000 rows).",
     "In the backend/data/ folder as a CSV file.",
     "Committed directly into git repository.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Have the path memorized."),

    (193, "Where is the benchmark script?",
     "In `backend/scripts/run_offline_benchmark.py`, which executes 5-fold cross-validation and writes metrics to JSON.",
     "In backend/scripts/run_offline_benchmark.py.",
     "Stand-alone executable Python script.",
     "backend/scripts/run_offline_benchmark.py",
     "Can be run via command line."),

    (194, "Where are the results stored?",
     "In `backend/data/ncfb_2026_cv_results.json`, which contains the fold F1 scores, confusion matrix, precision, recall, and 0.2% generalization gap.",
     "In backend/data/ncfb_2026_cv_results.json.",
     "JSON summary of cross-validation results.",
     "backend/data/ncfb_2026_cv_results.json",
     "Machine-readable benchmark output."),

    (195, "Can you run the benchmark live?",
     "YES. Running `python backend/scripts/run_offline_benchmark.py` takes under 3 seconds and prints all fold metrics, confusion matrices, and the 96.7% precision.",
     "Yes, I can run the script right now in the terminal to reproduce the results live.",
     "Executes 5-fold CV in ~2.8 seconds on CPU.",
     "backend/scripts/run_offline_benchmark.py",
     "Always offer to run this live for the panel!"),

    (196, "Can another developer reproduce your results?",
     "Yes. Any developer who clones the repo and runs `python backend/scripts/run_offline_benchmark.py` will get the exact same confusion matrix (TP=464, FP=16, FN=16, TN=9504) due to seed=42.",
     "Yes, anyone who downloads our project gets the exact same 96.7% precision score.",
     "100% reproducible benchmark pipeline.",
     "backend/scripts/run_offline_benchmark.py",
     "Scientific reproducibility is a huge strength."),

    (197, "What is the biggest weakness of synthetic data?",
     "It cannot model unknown zero-day criminal tactics, real sensor hardware dropouts, or non-stationary concept drift over years of live police operations.",
     "It is generated by rules we already know, while real criminals invent new tricks we haven't seen before.",
     "Lacks stochastic real-world noise and unexpected tradecraft shifts.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Shows mature engineering self-awareness."),

    (198, "What is precision?",
     "Precision is the proportion of flagged anomalies that were actually true criminal anomalies: Precision = TP / (TP + FP). It measures alert reliability and low false alarms.",
     "When the system screams 'Criminal!', how often is it actually right?",
     "TP / (TP + FP). High precision means investigators waste almost no time on false alarms.",
     "backend/scripts/run_offline_benchmark.py",
     "Crucial for preventing alert fatigue."),

    (199, "What is recall?",
     "Recall is the proportion of true criminal anomalies that were successfully detected by the system: Recall = TP / (TP + FN). It measures detection coverage.",
     "Out of all the real criminals out there, what percentage did we catch?",
     "TP / (TP + FN). High recall means very few criminals slip through undetected.",
     "backend/scripts/run_offline_benchmark.py",
     "Also known as Sensitivity or True Positive Rate."),

    (200, "What is F1-score?",
     "F1-score is the harmonic mean of precision and recall: F1 = 2 * (Precision * Recall) / (Precision + Recall), providing a single balanced metric for imbalanced datasets.",
     "The balance between not raising false alarms (precision) and not missing criminals (recall).",
     "Harmonic mean penalizes extreme imbalances between precision and recall.",
     "backend/data/ncfb_2026_cv_results.json",
     "Our F1-score is 0.967 (96.7%).")
]

print(f"Loaded {len(BATCH2_QUESTIONS)} questions in Batch 2.")
