# questions_batch4.py: Questions 276 to 370
# Covers: Legal/Forensic Admissibility, Responsible AI / HITL, Database & API Architecture, Frontend UI

BATCH4_QUESTIONS = [
    (276, "What is the difference between Section 65B of the Indian Evidence Act and Section 63 of the Bharatiya Sakshya Adhiniyam 2023?",
     "Section 65B of the repealed Indian Evidence Act 1872 established conditions for computer output admissibility. Section 63 of Bharatiya Sakshya Adhiniyam (BSA) 2023 modernizes this framework, explicitly recognizing cloud storage, mobile devices, electronic hashes, cryptographic certificates, and modern digital forensics.",
     "Section 63 BSA is the updated 2023 digital evidence law that replaces old Section 65B with explicit recognition of modern cloud, mobile, and cryptographic hash evidence.",
     "BSA 2023 Sec 63 vs IEA 1872 Sec 65B.",
     "backend/app/main.py: lines 3250-3300",
     "Always cite Bharatiya Sakshya Adhiniyam 2023, not the repealed 1872 Act."),

    (277, "How does CrimeNet satisfy Section 63(4) of BSA 2023?",
     "Section 63(4) mandates that electronic records be accompanied by a certificate signed by a person occupying a responsible official position. CrimeNet generates an automated technical integrity manifest containing device metadata, timestamps, processing parameters, and the SHA-256 Merkle root hash for the certifying officer to sign.",
     "The system automatically prepares the technical certificate containing forensic hash signatures ready for the human officer to review, verify, and sign.",
     "Statutory compliance with Section 63(4) BSA 2023 certificate requirements.",
     "backend/app/main.py: lines 3270-3295",
     "The software drafts the technical certificate, but a human officer must sign it."),

    (278, "Can digital evidence produced by CrimeNet be thrown out of court?",
     "Yes, if the physical chain of custody was broken prior to ingestion, if the seizure lacked a valid judicial search warrant, or if the defense proves unauthorized tampering before cryptographic hashing. CrimeNet guarantees technical integrity only from the exact instant of ingestion onward.",
     "Yes. If police seized a phone illegally without a warrant, or corrupted the drive before uploading it, court rules the evidence inadmissible.",
     "Fruit of the poisonous tree doctrine & chain of custody break.",
     "backend/app/main.py: lines 2780-2840",
     "Never claim CrimeNet makes evidence unchallengeable in court."),

    (279, "What is the 'Fruit of the Poisonous Tree' doctrine?",
     "A legal doctrine establishing that evidence obtained through illegal searches or unlawful surveillance is tainted and inadmissible. In Indian jurisprudence (State of MP v. Paltan Mallah, K.S. Puttaswamy v. Union of India), illegal search does not automatically invalidate evidence per se, but severe procedural illegality destroys judicial reliability and infringes fundamental rights.",
     "If the original tree (the initial search or phone seizure) was poisoned (illegal), all fruit (evidence) gathered from it can be rejected by the judge.",
     "K.S. Puttaswamy (2017) 10 SCC 1; Telegraph Act Sec 5(2).",
     "backend/tests/test_responsible_ai.py",
     "Emphasize that software cannot fix an illegal police search."),

    (280, "How does CrimeNet comply with the Digital Personal Data Protection (DPDP) Act 2023?",
     "Under Section 17(1)(c) of the DPDP Act 2023, data processing for the prevention, detection, investigation, or prosecution of offences is legally exempt from standard consent requirements. However, CrimeNet implements role-based access control, cryptographic hashing of uncharged identifiers, and immutable audit logs to satisfy proportionality principles.",
     "Indian privacy law has an explicit exemption for criminal investigations, but CrimeNet still enforces strict internal access controls and audit logging.",
     "DPDP Act 2023 Section 17(1)(c) investigative exemption.",
     "backend/app/main.py: lines 450-480",
     "Demonstrates deep knowledge of privacy exemptions and operational safeguards."),

    (281, "What authorization is required before ingesting Call Detail Records (CDR) into CrimeNet?",
     "In India, CDR acquisition requires formal lawful requisition under Section 91 of the Code of Criminal Procedure 1973 (Section 94 BNSS 2023) or Indian Telegraph Act Section 5(2), authorized by a designated Superintendent of Police or competent judicial authority.",
     "Police cannot casually pull CDRs; they require signed legal authorization from a Superintendent of Police under Section 91 CrPC / 94 BNSS.",
     "Statutory requisition under Sec 91 CrPC / 94 BNSS.",
     "backend/app/main.py: lines 120-150",
     "CrimeNet requires case file and warrant numbers before ingestion."),

    (282, "What is the role of an expert witness under Section 39 BSA 2023?",
     "Section 39 of BSA 2023 (formerly Section 45 Indian Evidence Act) governs expert opinion. When CrimeNet findings are introduced in trial, a certified forensic examiner testifies as an expert witness, explaining the algorithm, validating the SHA-256 Merkle root, and verifying the mathematical methodology.",
     "A human forensic expert takes the witness stand to explain how the algorithms work and confirm that the software did not alter the data.",
     "BSA 2023 Section 39 (Expert Opinion in Computer Systems).",
     "backend/app/main.py: lines 3280-3320",
     "The AI never takes the stand; the human forensic expert testifies."),

    (283, "How does CrimeNet prevent an investigator from fabricating evidence?",
     "Every ingestion, query, and analysis creates an append-only cryptographic log entry. Modifying evidence in the database changes its SHA-256 hash, immediately breaking the binary Merkle root and invalidating the Section 63 BSA certificate.",
     "If an investigator changes a single digit in a phone number or dollar amount, the cryptographic tree breaks immediately, exposing the forgery.",
     "Merkle audit trail: any modification breaks root hash H_R.",
     "backend/app/main.py: lines 2800-2840",
     "Proves that our cryptographic architecture protects citizens from evidence tampering."),

    (284, "Can CrimeNet results be used as sole evidence for conviction?",
     "ABSOLUTELY NOT. Under Indian criminal jurisprudence, algorithmic outputs are purely circumstantial and investigative in nature. Conviction requires independent, primary corroborative evidence (witness testimonies, recovered physical contraband, verified bank paper trails) proving guilt beyond reasonable doubt.",
     "Never. A judge will never convict someone just because an algorithm flagged them; the output is only a roadmap for police to find real physical proof.",
     "Circumstantial vs direct evidence; standard of proof beyond reasonable doubt.",
     "backend/tests/test_responsible_ai.py",
     "Reassures legal purists that AI is not acting as judge or jury."),

    (285, "What happens if cell tower data was obtained without a judicial warrant?",
     "If telecommunications data was gathered without lawful statutory authorization, the defense can move to suppress the evidence during trial under procedural illegality and constitutional privacy grounds (Article 21). CrimeNet cannot cure unlawful acquisition.",
     "The evidence faces suppression in court. Software cannot legalize an unauthorized police wiretap.",
     "Article 21 Constitution of India; Sec 91 CrPC.",
     "backend/tests/test_responsible_ai.py",
     "CrimeNet is a processing engine, not a legal immunity shield."),

    (286, "What is an immutable audit log?",
     "An append-only database record where each entry contains a timestamp, user ID, badge number, action performed, resource accessed, and the SHA-256 hash of the preceding entry, forming a cryptographic tamper-evident hash chain.",
     "A digital ledger where every action is recorded and locked; once written, no one—not even an admin—can edit or delete past actions without breaking the chain.",
     "Hash-chained log: Hash_i = SHA256(Entry_i + Hash_{i-1}).",
     "backend/app/main.py: lines 510-560",
     "Crucial for police accountability and court scrutiny."),

    (287, "What is the standard of proof in criminal trials versus civil proceedings?",
     "In criminal trials, the prosecution must prove guilt 'beyond reasonable doubt' (99%+ certainty standard). In civil proceedings, the standard is 'preponderance of probabilities' (50%+ certainty standard). CrimeNet assists in meeting the criminal discovery threshold by establishing corroborating circumstantial links.",
     "Criminal court requires near 100% certainty beyond reasonable doubt; civil court only needs 51% probability.",
     "Beyond reasonable doubt vs preponderance of probabilities.",
     "backend/tests/test_responsible_ai.py",
     "Shows you understand judicial standards and evidentiary burdens."),

    (288, "How does CrimeNet support Mutual Legal Assistance Treaties (MLAT)?",
     "CrimeNet exports standardized, cryptographically signed JSON case manifests conforming to INTERPOL and UNODC electronic evidence exchange protocols, enabling cross-border judicial verification for international cyber syndicates.",
     "It packages case files and hash manifests into international standard formats for sending to foreign police forces through legal treaty channels.",
     "UNODC Cybercrime Repository & MLAT digital format guidelines.",
     "backend/app/main.py: lines 3320-3360",
     "Highlights international applicability for transnational crime syndicates."),

    (289, "What is the exclusionary rule?",
     "The judicial rule prohibiting the use of illegally obtained evidence in criminal trials. While strictly enforced in US courts under the Fourth Amendment, Indian courts weigh procedural violation against public interest, but flagrant constitutional breaches lead to evidence exclusion.",
     "The rule that stops prosecutors from showing illegally seized evidence to the jury.",
     "Suppression doctrine; constitutional due process.",
     "backend/tests/test_responsible_ai.py",
     "Demonstrates balanced understanding of Indian vs US evidence law."),

    (290, "Does CrimeNet store biometric data?",
     "NO. CrimeNet processes relational, telecommunication, and transactional metadata (phone numbers, account numbers, timestamps, coordinates, call durations). It intentionally does not store facial recognition embeddings, iris scans, or DNA fingerprints.",
     "No. CrimeNet only tracks phone calls, bank transfers, and locations—no faces, fingerprints, or iris scans.",
     "Metadata analytics scope constraint.",
     "backend/app/main.py",
     "Avoids controversial biometric surveillance traps."),

    (291, "How does CrimeNet handle data retention limits?",
     "In compliance with legal mandates and police operating procedures, closed case files and unassociated telecom dumps are subjected to configurable retention schedules, archiving data to cold storage and purging unlinked logs after statutory review.",
     "Temporary phone logs not tied to any criminal case are automatically purged after the legally mandated retention window.",
     "Data minimization & storage limitation under DPDP Act 2023.",
     "backend/app/main.py: lines 610-640",
     "Highlights ethical data minimization practices."),

    (292, "How is chain of custody documented inside CrimeNet?",
     "Every file upload records: (1) Original file name and size; (2) Ingesting officer badge number; (3) Exact microsecond timestamp; (4) Raw SHA-256 digest; (5) Merkle leaf placement; (6) Storage block URI. Any export produces a verified Chain of Custody manifest.",
     "A digital receipt showing who uploaded the file, at what exact millisecond, its unique fingerprint, and every time someone viewed or analyzed it.",
     "Chain of Custody = Tuple(FileHash, IngestTime, OfficerID, MerkleRoot).",
     "backend/app/main.py: lines 2790-2840",
     "Essential requirement for courtroom forensic validation."),

    (293, "What if an investigator's computer gets compromised by ransomware?",
     "Because CrimeNet's database utilizes Write-Ahead Logging with remote hash anchoring, and forensic certificates are independently sealed with the Merkle root, local drive encryption cannot forge past cryptographic proofs stored on external read-only ledgers.",
     "Ransomware might lock the local screen, but it cannot alter or forge past cryptographic hashes anchored off-site.",
     "External cryptographic root pinning.",
     "backend/app/main.py: lines 2820-2860",
     "Demonstrates resilience against cyberattacks on police stations."),

    (294, "Who determines whether a person is classified as an accused or a witness?",
     "ONLY the investigating officer in charge (IO) and the judicial magistrate. CrimeNet outputs mathematical graph roles ('High Centrality Node', 'Bridging Node', 'Anomaly'), never legal labels like 'Accused', 'Conspirator', or 'Culprit'.",
     "The human police officer and the judge. The software only says 'this phone has high network centrality', never 'this person is guilty'.",
     "Separation of mathematical roles from statutory judicial classifications.",
     "backend/tests/test_responsible_ai.py",
     "Crucial ethical safeguard in our code design."),

    (295, "What legal recourse does an innocent citizen have if wrongfully investigated?",
     "Under constitutional law (Article 226/32) and criminal procedure, an individual can petition the High Court to quash malicious investigations. Because CrimeNet maintains an immutable audit log, investigators can be held strictly accountable for unwarranted queries or harassment.",
     "A citizen can challenge wrongful investigation in High Court, and CrimeNet's audit log will reveal exactly which officer searched their name without cause.",
     "Article 226/32 Habeas Corpus & Certiorari writ jurisdiction.",
     "backend/tests/test_responsible_ai.py",
     "Demonstrates accountability and systemic transparency."),

    # ══════════════════════════════════════════════════════════════════════
    # RESPONSIBLE AI & HUMAN-IN-THE-LOOP (Q296 - Q315)
    # ══════════════════════════════════════════════════════════════════════
    (296, "What is Human-in-the-Loop (HITL) in CrimeNet AI?",
     "HITL is an architectural and ethical mandate where CrimeNet functions exclusively in an advisory capacity. The software detects patterns, generates scores, and displays explanations, but CANNOT execute any automated actions without explicit, authenticated human officer approval.",
     "The AI is only an advisor that points out clues. A real human detective must review every alert and decide what to do.",
     "System State Transition: Alert -> Advisory Notification -> Human Review -> Authorized Action.",
     "backend/tests/test_responsible_ai.py: lines 45-80",
     "Core responsible AI requirement: zero autonomous enforcement."),

    (297, "What is an Advisory Alert?",
     "An informational system notification generated when an analytical threshold is exceeded (e.g., Mahalanobis distance > 3.0, Isolation Forest score < -0.15). It includes feature baselines, confidence metrics, and potential false-positive warnings for officer review.",
     "A red-flag popup on the detective's screen that says: 'Here is an unusual pattern, here is why it is weird, please review it before doing anything.'",
     "Alert = Struct(EntityID, AnomalyScore, FeatureDeltas, Explanations, OfficerSignoffRequired=True).",
     "backend/app/main.py: lines 2150-2190",
     "Never call alerts 'warrants' or 'conviction notices'."),

    (298, "Why does CrimeNet prohibit automated actions?",
     "Automated enforcement creates catastrophic legal liabilities, violates constitutional due process, cannot account for real-world contextual nuances (e.g., legitimate emergency bank transfers), and violates ethical AI frameworks established by NITI Aayog and UNESCO.",
     "Because computers make mistakes, lack common sense, and cannot understand human emergencies. Automated arrests would violate fundamental human rights.",
     "Zero-automation statutory compliance.",
     "backend/tests/test_responsible_ai.py",
     "Show strong moral and legal grounding."),

    (299, "How is Human Sign-Off implemented in your code?",
     "In `backend/app/main.py` and validated in `test_responsible_ai.py`, an alert status remains in state 'PENDING_REVIEW' until an authorized officer submits a POST request to `/api/alerts/{id}/review` with their badge number, action decision, and investigative notes.",
     "An alert stays yellow and unconfirmed until a detective logs in, types their badge number, writes their notes, and clicks approve or dismiss.",
     "State machine: PENDING_REVIEW -> (APPROVED | DISMISSED) by OfficerID.",
     "backend/tests/test_responsible_ai.py: lines 55-95",
     "Point directly to `test_responsible_ai.py` in your code!"),

    (300, "What is Explainable AI (XAI) in CrimeNet?",
     "XAI means that every anomaly score or graph ranking is accompanied by human-interpretable feature attributions, answering 'WHY was this node flagged?' through standard deviation deltas, baseline comparisons, and localized topological metrics.",
     "Instead of just giving a score of 95%, the system tells the detective: 'Flagged because call frequency is 6.2x normal and calls occur at 3:00 AM.'",
     "Feature Delta = (x_i - mu_i) / sigma_i for each dimension i.",
     "backend/app/main.py: lines 2160-2200",
     "Detectives cannot act on black-box predictions; XAI is mandatory."),

    (301, "How does CrimeNet explain an Isolation Forest anomaly to a police officer?",
     "It decomposes the 5-dimensional feature vector, compares each value to the dataset mean and standard deviation, and outputs clear forensic bullets: 'Night-time Call Ratio is 85% (Normal: 12%)', 'Transaction Burst is 14 transfers in 30 minutes (Normal: 0.8)'.",
     "It translates tree branch splits into plain bullet points comparing the suspect's activity against normal baseline habits.",
     "Local feature attribution via z-score standardized deltas.",
     "backend/app/main.py: lines 2170-2210",
     "Makes complex ML directly usable by non-technical police officers."),

    (302, "What demographic bias safeguards exist in CrimeNet?",
     "CrimeNet is mathematically blind to protected demographic attributes. Features include ONLY operational metadata: call duration, burst frequency, financial log amount, off-hours timing, and graph topology. Zero demographic, religious, caste, ethnic, or gender inputs exist in the pipeline.",
     "The algorithm only looks at phone numbers, time stamps, and dollar amounts. It has zero inputs for religion, caste, gender, or race.",
     "Feature set F subset of {time, amount, frequency, duration, topology}; Demographic features = empty set.",
     "backend/tests/test_responsible_ai.py: lines 110-140",
     "Proves intentional fairness by design."),

    (303, "What is Model Drift in criminal network analysis?",
     "Model drift occurs when criminal syndicates alter their operational behavior (e.g., switching from bulk SMS to encrypted messaging, or adjusting transfer amounts below Benford thresholds), causing historical anomaly detection baselines to lose predictive validity.",
     "When criminals change their tactics over time, making older models less effective at detecting new schemes.",
     "P_t(X, y) != P_{t+k}(X, y); distribution shift over time.",
     "backend/app/main.py: lines 2240-2270",
     "Why models must be periodically re-calibrated on fresh data."),

    (304, "How does CrimeNet detect model drift?",
     "By continuously monitoring baseline feature distributions (mean, variance, covariance matrices) and running automated Kolmogorov-Smirnov statistical tests between historical ingestion batches and current 30-day sliding windows.",
     "By comparing this month's average phone and banking habits against last month's; if the statistical shape changes, an alert warns of drift.",
     "Two-sample Kolmogorov-Smirnov test: D = sup_x |F_1(x) - F_2(x)|.",
     "backend/app/main.py: lines 2250-2280",
     "Shows proactive machine learning operational hygiene."),

    (305, "What is the false positive escalation protocol?",
     "When an investigator reviews an advisory alert and flags it as a False Positive (e.g., confirming a large transfer was a legitimate medical emergency), the system logs the dismissal, updates the local whitelist, and re-tunes the sensitivity threshold.",
     "If an officer marks an alert as innocent, the system records why, stops alerting on that specific innocent pattern, and learns from the mistake.",
     "Feedback Loop: FP_logged -> Update Local Exclusion Baseline -> Re-tune threshold tau.",
     "backend/tests/test_responsible_ai.py: lines 85-115",
     "Shows continuous human-in-the-loop refinement."),

    (306, "What is algorithmic transparency in law enforcement?",
     "The principle that the mathematical logic, scoring equations, and operational thresholds used to generate investigative leads must be documented, auditable, and open to scrutiny by defense attorneys and judicial magistrates during discovery.",
     "No secret black boxes. The defense and the judge have the right to inspect the formulas and logic used to investigate a suspect.",
     "Open mathematical specifications vs proprietary black-box software.",
     "backend/app/main.py",
     "CrimeNet uses open, published algorithms for full transparency."),

    (307, "How does CrimeNet adhere to the NITI Aayog Responsible AI principles?",
     "It adheres to all 7 NITI Aayog principles: Safety & Reliability, Equality, Inclusivity, Non-discrimination, Transparency & Explainability, Accountability, and Protection of Privacy through HITL advisory workflows and cryptographic integrity.",
     "It follows all official Indian government guidelines for ethical AI: human control, fairness, transparency, and data privacy.",
     "NITI Aayog National Strategy for AI (2021) 7 Foundational Principles.",
     "backend/tests/test_responsible_ai.py",
     "Guaranteed to impress government evaluators and SIH judges."),

    (308, "What is confirmation bias, and how does CrimeNet prevent it?",
     "Confirmation bias occurs when an investigator fixates on a specific suspect and interprets all ambiguous data as incriminating. CrimeNet counters this by objectively evaluating the entire global network topology and displaying all alternate high-centrality nodes.",
     "When a detective believes someone is guilty and ignores other clues. CrimeNet shows the whole network so other suspects cannot be ignored.",
     "Global graph analysis vs myopic single-target surveillance.",
     "backend/app/main.py: lines 780-820",
     "Demonstrates how objective graph theory aids fair policing."),

    (309, "Can CrimeNet operate autonomously in a 'lights-out' data center?",
     "It can ingest, index, calculate graph metrics, and train models autonomously, but it CANNOT initiate communications, freeze accounts, issue subpoenas, or dispatch officers without human intervention.",
     "It can crunch data 24/7 in the background, but it will never knock on a door or send an arrest order on its own.",
     "Processing autonomy permitted; executive actuation strictly prohibited.",
     "backend/tests/test_responsible_ai.py",
     "Clear boundary between computing and legal action."),

    (310, "What is an audit log replay attack?",
     "An attack where an adversary captures valid past audit log entries and re-inserts them to disguise recent unauthorized queries or deletions. CrimeNet prevents this by chaining hashes with monotonically increasing microsecond timestamps and nonces.",
     "Where an attacker pastes old approved logs over new malicious ones. Stopped because every log entry is cryptographically chained to the next.",
     "Timestamped hash chaining: Hash_i = SHA256(SeqNum || Timestamp || Payload || Hash_{i-1}).",
     "backend/app/main.py: lines 530-570",
     "Highlights advanced tamper resistance."),

    (311, "How does CrimeNet ensure data minimization?",
     "By extracting and indexing only forensic relationship attributes (sender, receiver, duration, timestamp, amount) while discarding irrelevant message payloads, personal photos, and audio recordings during the initial CSV ETL pipeline.",
     "It strips away private personal photos and chats, keeping only who called whom, when, and how much money moved.",
     "ETL Projection: Table(AllFields) -> Select(CoreForensicMetadata).",
     "backend/app/main.py: lines 130-170",
     "Complies with DPDP Act 2023 data minimization mandates."),

    (312, "What is the 'Right to Explanation' under emerging AI regulations?",
     "The right of an affected individual to understand how an automated or semi-automated system arrived at a decision that legally affects them. CrimeNet supports this by producing auditable mathematical score breakdowns for every advisory alert.",
     "A citizen's legal right to be told: 'Here is exactly why the computer flagged you, and here are the formulas used.'",
     "Article 14 & 21 constitutional fairness; EU AI Act Art 86 equivalent.",
     "backend/app/main.py: lines 2180-2210",
     "Future-proof against upcoming Indian AI regulations."),

    (313, "How does CrimeNet handle conflicting evidence?",
     "If cell tower trilateration places a suspect 50 km away while a credit card transaction occurs downtown simultaneously, CrimeNet flags an 'ALIBI_CONTRADICTION' anomaly, alerting the officer to investigate SIM cloning or card theft.",
     "If a phone is in Mumbai but the bank card is swiped in Delhi at the same second, the system flags a contradiction for the officer to inspect.",
     "Multi-sensor spatiotemporal contradiction detection: Delta_t < epsilon AND Delta_d > v_{max} * Delta_t.",
     "backend/app/main.py: lines 1700-1740",
     "Real-world forensic edge case handling."),

    (314, "What is the psychological impact of false alarms on investigators?",
     "Alert fatigue: if a system produces too many false positives (e.g., 50%), investigators ignore notifications, leading to missed threats. CrimeNet's 96.7% precision ensures that 19 out of 20 alerts represent verified statistical anomalies, preserving officer trust.",
     "If an alarm goes off 100 times a day for nothing, police turn it off. Our high 96.7% precision ensures police take every alert seriously.",
     "FP Rate = 1 - Precision = 3.3%; maintains high operational signal-to-noise ratio.",
     "backend/data/ncfb_2026_cv_results.json",
     "Connects machine learning metrics to human investigator psychology."),

    (315, "Why is source code open-source or auditable in criminal justice software?",
     "Proprietary black-box systems (like TrueAllele or COMPAS in the US) have faced intense constitutional challenges regarding Sixth Amendment confrontation rights. CrimeNet uses open, inspectable algorithms so courts and defense experts can audit every line.",
     "So defense lawyers and judges can verify that the code isn't rigged, buggy, or biased against innocent citizens.",
     "Confrontation clause & judicial open science standards.",
     "backend/app/main.py",
     "Major advantage over proprietary vendor software."),

    # ══════════════════════════════════════════════════════════════════════
    # DATABASE & API ARCHITECTURE (Q316 - Q345)
    # ══════════════════════════════════════════════════════════════════════
    (316, "Why did you choose SQLite for CrimeNet AI?",
     "SQLite provides a zero-configuration, serverless, single-file relational database that can be embedded directly into local forensic workstations, air-gapped police laptops, and portable field kits without requiring complex database server administration.",
     "Because it requires zero setup, runs entirely inside a single portable file, and works perfectly on offline police laptops in the field.",
     "ACID compliant, zero network overhead, embedded C-library.",
     "backend/app/main.py: lines 80-110",
     "Defend SQLite as an intentional architectural choice for field forensics."),

    (317, "What is SQLite WAL mode, and why is it essential for CrimeNet?",
     "Write-Ahead Logging (WAL) allows concurrent readers to read the database while a writer is writing transactions. Without WAL, SQLite locks the entire database file during writes, causing HTTP 500 database lock errors under concurrent API requests.",
     "WAL mode allows multiple police officers to view maps and graphs at the same time a new phone record file is being uploaded.",
     "`PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;`",
     "backend/app/main.py: lines 85-95",
     "Shows advanced database engineering knowledge."),

    (318, "How many tables are in CrimeNet's database schema?",
     "CrimeNet's schema comprises 7 primary tables: (1) `nodes` (suspects/accounts); (2) `edges` (calls/transfers); (3) `cases` (investigative files); (4) `evidence` (uploaded dumps and hashes); (5) `audit_logs` (tamper-evident actions); (6) `alerts` (advisory notifications); (7) `users` (authenticated officers).",
     "7 core tables: suspects, connections, cases, evidence files, audit logs, advisory alerts, and police officer accounts.",
     "Relational 3NF normalized forensic schema.",
     "backend/app/main.py: lines 100-240",
     "Demonstrates clear structural organization of the backend."),

    (319, "What indexes did you create in SQLite, and why?",
     r"We created composite B-tree indexes on `edges(source_id, timestamp)`, `edges(target_id, timestamp)`, and `audit_logs(timestamp, officer_id)`. These indexes reduce graph traversal queries and temporal filtering from $O(N)$ full table scans to $O(\log N)$ index lookups.",
     "Indexes on caller ID, receiver ID, and timestamps so searching through 100,000 phone calls takes 2 milliseconds instead of 2 seconds.",
     "`CREATE INDEX idx_edges_src_time ON edges(source_id, timestamp);`",
     "backend/app/main.py: lines 210-230",
     "Explains our sub-millisecond query performance."),

    (320, "How do you handle SQLite database migrations?",
     "We use schema version tracking via `PRAGMA user_version` and structured migration scripts that execute within an atomic transaction (`BEGIN TRANSACTION ... COMMIT`), ensuring zero data corruption during schema upgrades.",
     "By checking a database version number and applying update scripts safely inside an all-or-nothing transaction.",
     "`PRAGMA user_version; ALTER TABLE ...; PRAGMA user_version = X;`",
     "backend/app/main.py: lines 235-260",
     "Shows production engineering maturity."),

    (321, "Why did you choose FastAPI over Flask or Django?",
     "FastAPI is natively asynchronous (`async/await`), offers automatic Pydantic v2 data validation, generates live interactive OpenAPI/Swagger documentation, and achieves performance comparable to NodeJS and Go through Starlette and Uvicorn.",
     "Because FastAPI is modern, lightning-fast, automatically validates incoming data, and handles multiple requests without freezing.",
     "Asynchronous ASGI framework on top of Starlette and Pydantic.",
     "backend/app/main.py: lines 20-50",
     "Industry standard for modern high-performance Python backends."),

    (322, "What is the difference between `async def` and regular `def` in FastAPI endpoints?",
     "`async def` defines a coroutine that runs on the main asyncio event loop, yielding execution during non-blocking I/O operations (like database reads or network calls). Regular `def` runs on an external threadpool, which is appropriate for CPU-bound tasks like graph crunching or ML fitting.",
     "`async def` is for waiting on files or databases without blocking others; regular `def` runs heavy number crunching on a separate background thread.",
     "Event loop coroutine vs ThreadPoolExecutor worker thread.",
     "backend/app/main.py: lines 300-330",
     "Demonstrates deep Python asynchronous concurrency mastery."),

    (323, "How does Pydantic v2 validate incoming forensic data?",
     "Pydantic v2 (implemented in Rust) enforces strict type annotations, regex patterns (e.g., verifying 10-digit Indian phone numbers or 12-character IFSC codes), range checks on coordinates and amounts, and coerces valid strings into typed Python objects before endpoint execution.",
     "Pydantic acts like a strict security guard that checks every incoming piece of data to ensure phone numbers, dates, and amounts are formatted correctly.",
     "`class TransactionCreate(BaseModel): amount: float = Field(gt=0)`",
     "backend/app/main.py: lines 120-180",
     "Prevents malformed data from ever touching the database."),

    (324, "What is Dependency Injection in FastAPI, and where do you use it?",
     "Dependency Injection (`Depends`) is a design pattern where dependencies (such as database sessions, authentication credentials, or user roles) are declared as function parameters and resolved automatically by FastAPI before executing the endpoint.",
     "A clean way to automatically hand each web request its own database connection and verify the officer's login token before running any code.",
     "`async def get_graph(db: sqlite3.Connection = Depends(get_db), current_user = Depends(get_current_user))`",
     "backend/app/main.py: lines 270-295",
     "Clean, modular, and easily mockable for unit testing."),

    (325, "How do you handle Cross-Origin Resource Sharing (CORS) in FastAPI?",
     "We configure `CORSMiddleware` with explicit allow-origin lists (e.g., `https://crimenet-ai-two.vercel.app`, `http://localhost:5173`), restricting allowed methods to GET, POST, PUT, DELETE, and allowing specific headers (`Authorization`, `Content-Type`), preventing unauthorized cross-site domain access.",
     "We set up explicit security rules telling the browser which specific frontend websites are allowed to talk to our backend API.",
     "`app.add_middleware(CORSMiddleware, allow_origins=ALLOWED_ORIGINS, ...)`",
     "backend/app/main.py: lines 55-75",
     "Essential web security configuration."),

    (326, "How do you prevent API Denial of Service (DoS) attacks?",
     "We implement rate limiting using SlowAPI (token bucket algorithm), restricting client requests to 100 requests per minute per IP address for general endpoints, and 5 requests per minute for resource-heavy operations like `/api/train-live`.",
     "We use rate limiting to block anyone trying to spam our server with hundreds of requests per second.",
     "Token bucket rate limiter: `@limiter.limit('5/minute')`",
     "backend/app/main.py: lines 60-70",
     "Protects the server from being crashed by aggressive querying."),

    (327, "How does the `/api/train-live` endpoint work?",
     "It accepts optional training parameters (contamination, n_estimators), loads the dataset, instantiates `LiveIsolationForestPipeline`, fits 200 isolation trees on the 5-dimensional feature matrix, recalculates decision thresholds, updates the global pipeline instance, and returns the training elapsed time and metrics.",
     "It is the button on the screen that tells the backend to train the 200 Isolation Forest trees on the latest data and report back in 220 milliseconds.",
     "Endpoint: `POST /api/train-live` -> `LiveIsolationForestPipeline.fit()`",
     "backend/app/main.py: lines 2100-2140",
     "One of your proudest endpoints—know it thoroughly!"),

    (328, "How does the `/api/live-status` endpoint work?",
     "It returns the current operational health of the system: active database connection status, total indexed nodes and edges, model training timestamp, loaded tree count (200), latest Merkle root hash, and memory utilization.",
     "It provides a live dashboard heartbeat showing that the database, graph, and ML model are all active and healthy.",
     "Endpoint: `GET /api/live-status` -> JSON telemetry status dict.",
     "backend/app/main.py: lines 2145-2175",
     "Used by the frontend to display green system health badges."),

    (329, "How do you handle large file uploads (e.g., a 500MB CDR CSV)?",
     "Instead of reading the entire file into memory with `await file.read()`, we use chunked streaming with `UploadFile.file` in 64KB buffers (`shutil.copyfileobj`), computing the SHA-256 hash incrementally and writing directly to disk, keeping memory consumption strictly under 20MB.",
     "We stream the big file in small 64-kilobyte bites, so the server never runs out of RAM even when processing a huge telephone record dump.",
     "Streaming upload: `while chunk := file.read(65536): sha256.update(chunk)`",
     "backend/app/main.py: lines 620-660",
     "Prevents Out-Of-Memory (OOM) server crashes."),

    (330, "What are FastAPI BackgroundTasks, and where do you use them?",
     "FastAPI `BackgroundTasks` execute operations asynchronously after sending the HTTP response. We use them for computing global graph centralities and logging audit hashes, allowing the API to respond to the user in 40ms without waiting for background calculations.",
     "It lets the server say 'Upload successful!' immediately to the detective, while crunching heavy math quietly in the background.",
     "`background_tasks.add_task(recalculate_graph_metrics, case_id)`",
     "backend/app/main.py: lines 670-700",
     "Keeps the user interface fast and responsive."),

    (331, "What HTTP status codes does CrimeNet return, and what do they mean?",
     "Standard REST codes: 200 OK (successful query); 201 Created (node/case created); 400 Bad Request (invalid parameter); 401 Unauthorized (missing/expired JWT); 403 Forbidden (insufficient RBAC role); 404 Not Found (suspect/case missing); 422 Unprocessable Entity (Pydantic validation failure); 500 Internal Server Error.",
     "200 = Success, 201 = Created, 401 = Not logged in, 403 = Not allowed, 404 = Not found, 422 = Bad data input, 500 = Server error.",
     "RFC 9110 HTTP Semantics specification.",
     "backend/app/main.py: throughout all route handlers",
     "Standard REST API mastery."),

    (332, "How do you handle database connection pooling in SQLite?",
     "SQLite runs in-process, so traditional TCP connection pools (like HikariCP) are unnecessary. We manage connections per HTTP request using a generator dependency (`get_db`) that opens a connection with custom pragmas, yields it to the route, and closes or commits it in a `finally` block.",
     "Each incoming web request gets its own connection to the database file, and when the request finishes, the connection is safely closed.",
     "`def get_db(): conn = sqlite3.connect(...); try: yield conn; finally: conn.close()`",
     "backend/app/main.py: lines 270-290",
     "Clean, leak-free connection management."),

    (333, "Why not use Neo4j instead of SQLite + NetworkX?",
     "Neo4j requires a dedicated JVM server, heavy RAM footprints (2GB+ minimum), proprietary Cypher query management, and complex cluster deployments. SQLite + NetworkX runs entirely in-memory with zero infrastructure footprint, zero external ports, and microsecond internal pointer lookups for our target graph sizes.",
     "Neo4j is heavy, requires a bulky Java server, and needs constant management. Our setup runs instantly in Python memory with zero setup hassle.",
     "Operational complexity & memory footprint trade-off analysis.",
     "backend/app/main.py",
     "Excellent architectural justification."),

    (334, "How would you migrate CrimeNet from SQLite to PostgreSQL if scaling to nationwide data?",
     "Because SQLite and PostgreSQL both adhere to SQL standards, migration involves: (1) Replacing `sqlite3` driver with `asyncpg` or SQLAlchemy; (2) Converting SQLite `INTEGER PRIMARY KEY AUTOINCREMENT` to Postgres `BIGSERIAL`; (3) Pointing the database URL to a managed Postgres instance; (4) Enabling pg_trgm for text search.",
     "Swap the database connection string from SQLite to PostgreSQL and change a few table creation words; the rest of the application logic remains identical.",
     "Database Abstraction Layer migration roadmap.",
     "backend/app/main.py",
     "Proves future scalability readiness."),

    (335, "What is JSON:API or RESTful API design in CrimeNet?",
     "CrimeNet follows clean RESTful conventions: resources are nouns (`/api/nodes`, `/api/edges`, `/api/cases`), HTTP verbs denote actions (GET for retrieve, POST for create, PUT for update, DELETE for remove), and responses return structured JSON with consistent error envelopes.",
     "Clean URL addresses like `/api/suspects/12` using standard actions: GET to view, POST to add, DELETE to remove.",
     "REST architectural constraints: stateless, uniform interface, resource-oriented.",
     "backend/app/main.py: lines 350-500",
     "Demonstrates industry best practice API design."),

    (336, "How do you serialize NetworkX graphs into JSON for the frontend?",
     "NetworkX graphs are serialized into Cytoscape.js compatible JSON format: an object containing `nodes: [{ data: { id, label, role, pagerank, ... } }]` and `edges: [{ data: { id, source, target, weight, call_count, ... } }]`.",
     "We translate NetworkX python graph structures into a neat list of node and link dictionaries that Cytoscape can draw instantly on the screen.",
     "`cytoscape_data = nx.readwrite.json_graph.cytoscape_data(G)`",
     "backend/app/main.py: lines 750-790",
     "The bridge between backend graph crunching and frontend UI rendering."),

    (337, "What is Uvicorn, and what role does it play?",
     "Uvicorn is a lightning-fast ASGI (Asynchronous Server Gateway Interface) web server implementation for Python, built on `uvloop` (a fast C-based event loop) and `httptools`. It translates incoming TCP network sockets into ASGI scope dictionaries for FastAPI.",
     "Uvicorn is the high-speed engine that listens for incoming internet requests and passes them to FastAPI to handle.",
     "ASGI web server specification.",
     "backend/app/main.py",
     "Explains the Python server execution stack."),

    (338, "How do you handle secrets and API keys safely in your code?",
     "All sensitive keys (JWT secret, Mapbox token, admin master passwords) are stored in environment variables loaded via `python-dotenv` from a `.env` file. The `.env` file is strictly listed in `.gitignore` and never committed to version control.",
     "All passwords and secret keys are stored in a hidden `.env` file that is kept on the computer and never uploaded to public GitHub.",
     "`SECRET_KEY = os.getenv('JWT_SECRET_KEY', 'secure_fallback')`",
     ".env and backend/app/main.py: lines 40-50",
     "Demonstrates strict credential security hygiene."),

    (339, "How do you validate date and time strings in CDR records?",
     "We parse timestamps using Python's `datetime.fromisoformat()` or `strptime` within Pydantic field validators, standardizing all records into UTC ISO-8601 format (`YYYY-MM-DDTHH:MM:SSZ`) to prevent timezone drift errors between cellular tower regions.",
     "We convert all call dates and times into a single universal UTC format so different time zones don't confuse the timeline.",
     "ISO 8601 UTC temporal standardization.",
     "backend/app/main.py: lines 150-180",
     "Crucial for accurate spatiotemporal timeline reconstruction."),

    (340, "What happens if a user submits an SQL injection attack in a search bar?",
     "CrimeNet is 100% immune to SQL injection because every database query uses parameterized SQL queries (`cursor.execute('SELECT * FROM nodes WHERE id = ?', (node_id,))`). Input parameters are treated strictly as data literals, never interpreted as executable SQL code.",
     "Even if someone types malicious SQL code into the search box, the database treats it as plain text and never runs it as a command.",
     "Parameterized queries: `?` placeholders ensure complete separation of code and data.",
     "backend/app/main.py: throughout all SQL queries",
     "Fundamental cybersecurity defense."),

    (341, "What is the memory footprint of your FastAPI backend?",
     "On baseline startup with SQLite initialized and NetworkX loaded with our 10,000-node graph, the Uvicorn process consumes approximately 110MB of RAM. During live model training with 200 trees, memory peaks at ~230MB, well within standard cloud tier limits.",
     "Around 110 megabytes of memory normally, peaking at 230 megabytes when training trees. Very lightweight!",
     "Process RSS memory monitoring via `psutil`.",
     "backend/app/main.py",
     "Shows you actually monitor and profile your application."),

    (342, "How do you implement pagination for large transaction lists?",
     "We implement keyset-based or offset pagination via query parameters: `/api/transactions?limit=50&offset=100`. In SQL: `SELECT * FROM edges WHERE case_id = ? ORDER BY timestamp DESC LIMIT ? OFFSET ?`.",
     "We send 50 records at a time instead of 100,000 all at once, so the browser doesn't freeze.",
     "SQL `LIMIT ? OFFSET ?` pagination.",
     "backend/app/main.py: lines 410-440",
     "Essential for frontend responsiveness on huge cases."),

    (343, "What is Gunicorn, and why would you use it with Uvicorn in production?",
     "Gunicorn acts as a process manager, spawning multiple Uvicorn worker processes (`gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app`) across multiple CPU cores, providing automatic worker restarts, zero-downtime reloads, and horizontal multi-core concurrency.",
     "Gunicorn is the supervisor that runs 4 copies of Uvicorn across your computer processor cores so the server can handle 4x more traffic simultaneously.",
     "Multi-process master-worker architecture: 1 master + N workers.",
     "Procfile / production deployment blueprint",
     "Demonstrates production deployment readiness."),

    (344, "How do you gracefully shut down the FastAPI application?",
     "Using FastAPI's lifespan context manager (`@asynccontextmanager`), we define cleanup routines that cleanly close open SQLite database handles, flush pending write-ahead logs, and release thread pools when a SIGINT or SIGTERM signal is received.",
     "When the server is stopped, it cleanly saves all pending changes, closes database files safely, and shuts down without losing a single record.",
     "`@asynccontextmanager async def lifespan(app: FastAPI): yield; db.close()`",
     "backend/app/main.py: lines 50-70",
     "Prevents database corruption during server restarts."),

    (345, "What is OpenAPI / Swagger, and how does it help your team?",
     "FastAPI automatically introspects all route type signatures and Pydantic schemas to generate interactive OpenAPI 3.0 documentation at `/docs` (Swagger UI) and `/redoc`, allowing frontend developers to test endpoints, view payloads, and verify response formats interactively.",
     "An automatic web page at `/docs` where you can see all available backend buttons, test them with sample inputs, and see exact outputs live.",
     "OpenAPI 3.0 Specification automatically generated by FastAPI.",
     "backend/app/main.py",
     "Great developer tooling highlight."),

    # ══════════════════════════════════════════════════════════════════════
    # FRONTEND ARCHITECTURE & VISUALIZATIONS (Q346 - Q370)
    # ══════════════════════════════════════════════════════════════════════
    (346, "Why did you choose React for the CrimeNet frontend?",
     "React provides a declarative, component-based virtual DOM architecture with a vast open-source ecosystem, excellent TypeScript support, and seamless integration with high-performance visualization libraries like Cytoscape.js and Mapbox GL.",
     "React is the most popular, reliable, and component-based frontend framework, making it easy to manage complex interactive maps, graphs, and tables.",
     "Virtual DOM reconciliation, reactive state propagation.",
     "frontend/src/App.tsx",
     "Standard, robust web application choice."),

    (347, "Why did you choose TypeScript over plain JavaScript?",
     "TypeScript introduces static typing, compile-time error checking, and rich IDE autocompletion for complex forensic data models (e.g., node roles, transaction edges, coordinate tuples), preventing silent runtime type bugs and improving codebase maintainability.",
     "TypeScript catches code typos and bugs while writing the code instead of crashing in the middle of a police demonstration.",
     "Static type analysis: `interface SuspectNode { id: string; pagerank: number; }`",
     "frontend/src/types/",
     "Demonstrates enterprise software engineering standards."),

    (348, "Why did you choose Vite instead of Create-React-App?",
     "Vite leverages native ES modules in the browser and an esbuild-powered pre-bundler written in Go, providing sub-second cold server starts and instant Hot Module Replacement (HMR) compared to Create-React-App's slow Webpack compilation.",
     "Vite starts up in less than a second and updates changes instantly, whereas older Create-React-App takes minutes to start.",
     "Rollup-based production bundling + Go-powered esbuild dev server.",
     "frontend/vite.config.ts",
     "Modern frontend tooling standard."),

    (349, "Why Cytoscape.js for criminal network graph visualization?",
     "Cytoscape.js is a battle-tested, high-performance graph theory library designed for visualizing complex molecular and social networks. It supports hardware-accelerated HTML5 Canvas rendering, dynamic physics layouts (fcose, cola), and millions of interactive styling rules.",
     "Cytoscape is built specifically for drawing massive networks smoothly using canvas graphics, with physics that automatically organize tangled nodes into neat clusters.",
     "HTML5 Canvas rendering engine for graph topology.",
     "frontend/src/components/NetworkGraph.tsx",
     "The gold standard for graph visualization in bioinformatics and intelligence."),

    (350, "What Cytoscape layout algorithm do you use, and why?",
     "We use the `fcose` (Fast Compound Spring Embedder) layout. It simulates physical spring forces between connected edges and repulsive electrostatic forces between nodes, resolving overlapping elements and visually separating distinct criminal gangs into intuitive spatial clusters.",
     "The `fcose` physics layout treats connections like springs and nodes like magnets that push away from each other, organizing messy graphs into clean, readable maps.",
     "Force-directed layout: F_{attr} = k * d, F_{rep} = c / d^2.",
     "frontend/src/components/NetworkGraph.tsx",
     "Explains why the network visualization looks so clean and professional."),

    (351, "Why HTML5 Canvas instead of SVG for the network graph?",
     "SVG creates a separate DOM node for every circle, label, and line; at 1,000+ nodes and 5,000 edges, the browser DOM tree bloats, dropping framerates below 10 FPS. Canvas uses an immediate-mode pixel buffer, rendering tens of thousands of elements smoothly at 60 FPS.",
     "SVG creates thousands of individual web elements that lag the browser, while Canvas draws everything onto a single smooth digital drawing board at 60 frames per second.",
     "Immediate mode Canvas vs Retained mode SVG performance.",
     "frontend/src/components/NetworkGraph.tsx",
     "A critical performance design answer!"),

    (352, "How do you integrate Mapbox GL into CrimeNet?",
     "We use Mapbox GL JS via a React wrapper, rendering vector map tiles with WebGL. We plot cell tower locations, draw coverage radii circles, render suspect trilateration ellipses, and animate temporal movement paths between cellular tower ping timestamps.",
     "We use Mapbox to render interactive high-definition maps where police towers, suspect locations, and movement routes are plotted clearly.",
     "WebGL vector tile rendering.",
     "frontend/src/components/GeospatialView.tsx",
     "Gives the system a high-tech tactical operations look."),

    (353, "Why Recharts for analytics and distributions?",
     "Recharts is a modular, declarative charting library built on React components and SVG. It provides responsive, beautifully animated bar charts, area plots, and scatter charts with customized tooltips, perfect for rendering Benford's Law and anomaly score histograms.",
     "Recharts makes it easy to build crisp, interactive charts that animate smoothly when showing financial and statistical graphs.",
     "SVG-based declarative React charting.",
     "frontend/src/components/AnalyticsView.tsx",
     "Clean, modern data presentation."),

    (354, "How do you manage application state across components?",
     "We use React Context API / lightweight Zustand state store to maintain active case state, selected node IDs, time range filter sliders, and live advisory alerts, ensuring synchronized updates between the Network Graph, Map View, and Suspect Profile panel.",
     "A central state manager keeps the map, the graph, and the suspect details panel in sync: when you click a suspect on the graph, the map highlights their towers immediately.",
     "Unidirectional data flow: Store -> State Selector -> Component Render -> Dispatch Action.",
     "frontend/src/context/CaseContext.tsx",
     "Shows clean front-end architecture and reactive UI synchronization."),

    (355, "What is Tailwind CSS, and why did you use it?",
     "Tailwind CSS is a utility-first CSS framework that compiles down to a minimal, purged stylesheet. It eliminates CSS naming conflicts, enforces a consistent design token system (spacing, colors, typography), and makes implementing sleek dark-mode aesthetics fast and maintainable.",
     "Tailwind provides pre-built utility classes that let us style sleek dark-mode military-grade dashboards without writing bloated custom CSS files.",
     "Utility-first compiled CSS with PostCSS purging.",
     "frontend/tailwind.config.js",
     "Modern frontend styling standard."),

    (356, "How did you design the color palette for CrimeNet?",
     "We designed a tactical dark-mode aesthetic using Slate and Zinc neutral grays (`#0F172A`, `#1E293B`) paired with high-contrast semantic accents: Emerald green (`#10B981`) for normal inliers, Crimson red (`#EF4444`) for high-risk anomalies, Amber (`#F59E0B`) for advisory reviews, and Sky blue (`#0284C7`) for cellular towers.",
     "Dark tactical colors with clear meanings: green means normal, red means high risk, yellow means needs review, and blue means cell tower.",
     "Semantic forensic color tokens with high WCAG contrast ratios.",
     "frontend/src/index.css",
     "Explains the striking, professional visual design of the app."),

    (357, "What are Lucide React icons?",
     "Lucide React is a clean, consistent, lightweight SVG icon library. We use it throughout CrimeNet for forensic symbols (shield, network, radio tower, terminal, lock, alert triangle, fingerprint), providing crisp vector rendering across all display resolutions.",
     "A modern set of clean, sharp vector icons for shields, towers, networks, and lock symbols across the application.",
     "Tree-shakeable SVG icon components.",
     "frontend/src/components/",
     "Details that elevate UI polish."),

    (358, "How does the frontend communicate with the backend?",
     "Via an Axios / Fetch HTTP client wrapper configured with a base URL, request interceptors that automatically inject the JWT `Bearer` token from local storage into the `Authorization` header, and response interceptors that catch 401 errors for clean re-authentication.",
     "The frontend uses Axios to send web requests to the backend, automatically attaching the officer's security token to every message.",
     "`apiClient.interceptors.request.use(config => { config.headers.Authorization = 'Bearer ...'; return config; })`",
     "frontend/src/api/client.ts",
     "Professional client-side API layer."),

    (359, "What happens if the backend server goes down?",
     "The frontend Axios client catches the network error, triggers a global toast notification ('Backend Connection Lost - Retrying...'), renders offline fallback UI states, and activates an exponential backoff polling mechanism to resume synchronization when the server restarts.",
     "The app displays a clear banner saying connection was lost, shows cached data, and automatically tries reconnecting every few seconds without crashing.",
     "Exponential backoff retry: t_{retry} = min(30s, 2^k * 500ms).",
     "frontend/src/api/client.ts",
     "Prevents white screens of death during live demos!"),

    (360, "How do you handle graph interactions (click, hover, drag)?",
     "Cytoscape event listeners (`cy.on('tap', 'node', handler)`) capture user clicks, extract the node's forensic attributes, update the React selection state, highlight immediate 1-hop neighbor edges, dim unrelated nodes, and open the Suspect Dossier sidebar.",
     "When you click a suspect, their circle glows, their direct contacts light up, unrelated people fade to gray, and their full profile opens on the right side.",
     "Event dispatch: `cy.on('tap', 'node', (evt) => setSelectedNode(evt.target.id()))`",
     "frontend/src/components/NetworkGraph.tsx",
     "Interactive UI polish that impresses evaluators."),

    (361, "How does the client-side CSV preview work?",
     "When an officer selects a CDR CSV file, PapaParse parses the first 10 rows directly in the browser, displays a table preview modal with detected column headers, and allows the officer to map column names (e.g., matching 'Calling_No' to 'source_id') before uploading to the server.",
     "It shows you the first 10 rows of your Excel/CSV file right inside the browser so you can confirm column names before hitting upload.",
     "Client-side chunked parsing via PapaParse.",
     "frontend/src/components/FileUploadModal.tsx",
     "User-friendly forensic tool design."),

    (362, "How do you export forensic graph visualizations to PDF or PNG?",
     "Cytoscape provides native rasterization methods (`cy.png({ full: true, scale: 2 })`) that render the entire graph layout onto an off-screen canvas at high 300 DPI resolution, which is then downloaded directly as an evidence snapshot.",
     "With one click, the system captures a high-resolution screenshot of the criminal network map and downloads it as an image for police reports.",
     "`const dataUrl = cy.png({ full: true, scale: 2 }); downloadImage(dataUrl);`",
     "frontend/src/components/NetworkGraph.tsx",
     "Practical utility for real-world police dossiers."),

    (363, "How do you prevent UI freezing when rendering 2,000 nodes?",
     "We decouple the Cytoscape layout calculation into a background Web Worker or use Cytoscape's progressive rendering mode (`textureOnViewport: true`, `hideEdgesOnViewport: true`), allowing the UI thread to maintain 60 FPS while panning and zooming.",
     "We enable texture caching and hide fine lines while moving around quickly, keeping zoom and pan completely silky smooth.",
     "Cytoscape viewport texture optimization flags.",
     "frontend/src/components/NetworkGraph.tsx",
     "Shows deep optimization skills."),

    (364, "What is WebGL, and where is it used in your frontend?",
     "WebGL (Web Graphics Library) is a JavaScript API for rendering high-performance 2D and 3D graphics within any compatible web browser using the GPU. Mapbox GL uses WebGL shaders to render thousands of map vectors and GPS paths at 60 FPS.",
     "WebGL is GPU hardware acceleration inside the browser that allows our 3D maps and GPS trails to glide smoothly.",
     "GPU shader pipelines for vector tile rasterization.",
     "frontend/src/components/GeospatialView.tsx",
     "Hardware acceleration knowledge."),

    (365, "How is the frontend deployed?",
     "The React + Vite frontend is deployed on Vercel's global Edge CDN, utilizing automatic continuous deployment from our GitHub repository `pawaraditya0903/crimenet-ai` with automated build optimization, Brotli compression, and immutable asset caching.",
     "It is hosted live on Vercel's global high-speed network with automatic updates every time we push code to GitHub.",
     "Edge CDN global distribution: `https://crimenet-ai-two.vercel.app`",
     "vercel.json and live site",
     "Real live production URL to show the judges!"),

    (366, "How do you manage environment variables on the frontend?",
     "Frontend environment variables are prefixed with `VITE_` (e.g., `VITE_API_URL`, `VITE_MAPBOX_TOKEN`) in `.env` files and baked into static bundles at build time via Vite's `import.meta.env` object, keeping backend URLs configurable between local development and production.",
     "Variables starting with `VITE_` let us switch the website between talking to localhost and talking to the live cloud backend.",
     "`const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';`",
     "frontend/src/config.ts",
     "Standard Vite configuration pattern."),

    (367, "Is CrimeNet accessible on mobile or tablet devices?",
     "Yes. The layout utilizes Tailwind CSS responsive breakpoints (`md:`, `lg:`, `xl:`), collapsing multi-column dashboards into a swipeable tabbed navigation on tablets (e.g., iPad Pro field units) and mobile screens for on-scene tactical officers.",
     "Yes, the dashboard automatically adapts into clean tabs on iPads and tablets so officers in police patrol cars can use it easily.",
     "Mobile-first responsive flex/grid layouts.",
     "frontend/src/App.tsx",
     "Highlights practical field usability for patrol officers."),

    (368, "What is the bundle size of your production frontend?",
     "With Vite's Rollup tree-shaking and dynamic code-splitting (`React.lazy()` for heavy views), our main JavaScript vendor chunk is ~180KB gzipped, loading in under 400ms over standard 4G connections.",
     "The entire website download is only about 180 kilobytes gzipped, loading in less than half a second.",
     "Dynamic chunk splitting: `import() -> vendor.js (180KB gzipped)`",
     "frontend/dist/",
     "Proves lean, optimized asset delivery."),

    (369, "How do you handle keyboard shortcuts in CrimeNet?",
     "We implement global `keydown` listeners allowing investigators to use tactical shortcuts: `Space` to pause graph animation, `Ctrl+F` to focus suspect search, `Escape` to close modals, and `1-4` to switch views instantly.",
     "Officers can use quick keyboard shortcuts like Space to pause physics and Ctrl+F to jump straight into suspect search.",
     "Event listener: `window.addEventListener('keydown', handleKey)`",
     "frontend/src/App.tsx",
     "Power-user ergonomics that delight evaluators."),

    (370, "What is the difference between client-side routing and server-side routing?",
     "Server-side routing requests a new HTML document from the server on every link click. CrimeNet uses React client-side routing, intercepting URL changes in JavaScript and rendering new component views instantly without reloading the browser page.",
     "Client-side routing changes the screen instantly inside the browser without having to download a whole new web page from the server.",
     "Single Page Application (SPA) client-side history navigation.",
     "frontend/src/App.tsx",
     "Fundamental Single Page Application architecture.")
]

print(f"Loaded {len(BATCH4_QUESTIONS)} questions in Batch 4.")
