# questions_batch1.py: Questions 1 to 100
# Covers: Project, Problem, Workflow, Limitations, Architecture, Knowledge Graph, PageRank, Centralities

BATCH1_QUESTIONS = [
    (1, "What is CrimeNet AI?",
     "CrimeNet AI is a cyber-forensic decision-support platform that unifies four disconnected data silos—telecom Call Detail Records, hawala banking ledgers, highway toll cameras, and dark-web intercepts—into an interactive 48-node knowledge graph.",
     "It turns fragmented spreadsheets into an interconnected map where investigators can see the full criminal syndicate in seconds.",
     "Relational SQL databases degrade polynomially (O(N^k)) during multi-hop JOINs; CrimeNet represents entities as in-memory graph G=(V,E).",
     "backend/app/main.py: lines 300-350",
     "Never describe it as an autonomous police robot; it is an advisory decision-support platform."),

    (2, "What problem does it solve?",
     "It solves the investigative silo problem where officers spend months manually cross-referencing disparate Excel sheets across telecom operators, banks, and transport databases to track proxy cut-outs and laundering loops.",
     "Criminals divide their operations across multiple channels; CrimeNet joins those scattered breadcrumbs automatically.",
     "Eliminates O(N^k) relational query bottlenecks by treating relationships as direct pointers in an adjacency graph.",
     "backend/app/main.py",
     "Do not say it solves all crime; state that it accelerates link analysis and multi-sensor cross-correlation."),

    (3, "Why did you build this project?",
     "I built CrimeNet AI to eliminate investigative blind spots in complex financial fraud and organized narcotics syndicates where kingpins hide behind layers of burner SIMs and mule bank accounts.",
     "To give investigators a visual radar that exposes the hidden bosses who never carry contraband themselves.",
     "Automates graph centralities, unsupervised anomaly detection, and radio trilateration.",
     "backend/app/main.py",
     "Focus on forensic link analysis rather than generic crime reporting."),

    (4, "What is the main objective?",
     "The main objective is to accelerate syndicate link analysis from months to seconds by automating multi-sensor data fusion, kingpin centrality scoring, circular money-trail detection, and court-compliant cryptographic evidence logging.",
     "Uncover the syndicate kingpin, track the money loop, and lock the evidence with zero tampering.",
     "Three core pillars: (1) Graph fusion; (2) Unsupervised anomaly detection; (3) SHA-256 Merkle tree evidence locking.",
     "backend/app/main.py",
     "Never state the objective is 'autonomous sentencing or arrest'."),

    (5, "Who are the target users?",
     "The target users are cybercrime investigators, economic offense wings, intelligence analysts, and forensic auditors.",
     "Law enforcement officers and financial intelligence units investigating organized syndicates.",
     "Requires role-based access control (RBAC) to ensure strict evidentiary chain of custody.",
     "src/App.tsx, backend/app/main.py",
     "Not intended for the general public; it is an analytical law-enforcement tool."),

    (6, "What is the main innovation?",
     "The main innovation is the unified fusion of multi-sensor forensic streams (telecom, banking, ANPR) into an interactive mathematical knowledge graph paired with explainable unsupervised anomaly detection and tamper-proof SHA-256 Merkle trees.",
     "Combining social network theory, machine learning, and cryptography into one unified investigative workstation.",
     "Fuses NetworkX graph theory, Scikit-Learn Isolation Forest, WLS radio trilateration, and Merkle tree hashing.",
     "backend/app/main.py",
     "Don't just mention AI; highlight the multi-sensor graph fusion."),

    (7, "What makes CrimeNet AI different from existing systems?",
     "Legacy police databases like CCTNS are static SQL search repositories where an officer must already know a suspect's name or FIR number. CrimeNet AI is an active graph analytical engine that automatically discovers unknown proxy connections, scores kingpins via PageRank, and uncovers circular Hawala smurfing.",
     "CCTNS is like a phone directory where you must know who to look up. CrimeNet AI is a social network map that highlights the hidden boss automatically.",
     "Graph-native adjacency pointers vs relational table JOINs.",
     "src/components/NetworkGraph.tsx",
     "Never disparage CCTNS; acknowledge it as an operational repository while CrimeNet is an analytical engine."),

    (8, "Is this a real production police system?",
     "No. CrimeNet AI is a high-fidelity investigative prototype and research benchmark platform.",
     "It is a research-grade forensic prototype demonstrating cutting-edge algorithms on realistic benchmarks.",
     "Evaluated on synthetic benchmark NCFB-2026 under 5-Fold Stratified Cross-Validation.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "TRAP: Never claim your project is currently deployed in real police headquarters."),

    (9, "Does it use real police data?",
     "No. Under Section 5(2) of the Indian Telegraph Act, the Digital Personal Data Protection (DPDP) Act 2023, and banking secrecy laws, distributing real citizen telecom intercepts or bank account logs is strictly illegal. We evaluated on our synthetic National Cyber Forensic Benchmark (NCFB-2026).",
     "Publishing real citizen phone calls on GitHub violates statutory privacy laws. We calibrated realistic synthetic distributions instead.",
     "Log-normal financial transactions (mu=9.2, sigma=1.8) and power-law degree distributions.",
     "backend/data/ncfb_2026_benchmark_10k.csv",
     "Interviewers will respect your strict understanding of statutory privacy laws."),

    (10, "What are the major modules?",
     "CrimeNet AI consists of 6 major modules: (1) Ingestion & Entity Resolution; (2) NetworkX Knowledge Graph Engine; (3) Live Isolation Forest & Mahalanobis Anomaly Engine; (4) Telecom WLS Trilateration & 2D Kalman Kinematics; (5) Hawala Smurfing & Benford Chi-Square Accounting; and (6) SHA-256 Merkle Tree Evidence Ledger.",
     "Ingestion -> Graph Mapping -> ML Anomaly Detector -> Telecom Radar -> Hawala Checker -> Tamper-Proof Evidence Locker.",
     "Decoupled FastAPI backend and React 19 frontend.",
     "backend/app/main.py, src/App.tsx",
     "Ensure you can list all 6 modules smoothly without hesitation."),

    (11, "Explain the complete workflow.",
     "Raw multi-sensor data enters FastAPI -> Entity resolution unifies PAN and phone records -> NetworkX builds the 48-node graph -> PageRank and Betweenness identify key entities -> Isolation Forest flags statistical anomalies -> Advisory alerts appear on the React 19 HUD -> Investigator conducts badge review -> Confirmed evidence is locked in a SHA-256 Merkle tree.",
     "From raw CSV spreadsheets to an interactive graph map, to machine learning alerts, to a court-ready evidence dossier.",
     "Raw Data -> Canonicalization -> In-Memory Graph -> Centrality/ML Scoring -> HITL Review -> Merkle Root Hash.",
     "backend/app/main.py",
     "Always highlight that human investigator review occurs before evidence locking."),

    (12, "Explain the project in 30 seconds.",
     "In organized crime, kingpins hide behind layers of burner SIMs and mule accounts. CrimeNet AI fuses multi-sensor logs into an interactive knowledge graph, using PageRank, tuned Isolation Forest with 96.7% precision on our 10k benchmark, and 3-tower radio trilateration to expose syndicate bosses and circular Hawala smurfing in seconds, locking evidence with SHA-256 Merkle trees.",
     "A high-impact summary covering the problem, technology, precision, and legal compliance.",
     "Graph theory + Tree anomaly detection + Radio physics + Cryptographic hashing.",
     "backend/app/main.py",
     "Practice reciting this 30-second response in one breath."),

    (13, "Explain the project in 1 minute.",
     "Add the decoupled React 19/FastAPI stack, explainable AI feature baselines, the 0.2% generalization gap, and the Human-in-the-Loop advisory review framework with zero autonomous enforcement.",
     "A complete architectural overview suitable for senior panel members.",
     "Includes full tech stack, validation metrics, and responsible AI governance.",
     "backend/app/main.py, src/App.tsx",
     "Avoid rambling; stick to verified architectural metrics."),

    (14, "Explain the project without using the word AI.",
     "CrimeNet AI is a forensic data fusion platform. It converts tabular telecom logs and banking transactions into a mathematical relational network. It applies graph matrix algorithms—specifically PageRank and Betweenness Centrality—to uncover hidden hub entities, uses statistical tree partitioning and Mahalanobis distance to flag statistical transaction outliers, solves non-linear radio path-loss equations across cell towers to approximate burner phone coordinates, and generates cryptographically signed tamper-proof evidence records.",
     "Strip away the buzzwords: it is pure discrete mathematics, linear algebra, graph theory, and cryptographic hashing.",
     "Graph theory + Tree-based statistical partitioning + Covariance matrix inversion + Cryptographic hashing.",
     "backend/app/main.py",
     "This question tests if you truly understand the mathematical foundations."),

    (15, "What is the biggest limitation of your project?",
     "Our prototype requires pre-structured digital sensor feeds (CSV/JSON/SQL). In real police operations, substantial evidence arrives in handwritten case diaries, scanned FIRs, or blurry photocopies. In our next production phase, we would integrate an OCR ingestion pipeline to bridge that physical-to-digital gap.",
     "The software expects clean digital data, whereas police stations often deal with messy physical paper records.",
     "Requires semi-structured schema mapping; lacks native optical character recognition for handwritten text.",
     "backend/app/main.py",
     "Panels appreciate honesty about technical limitations; never claim your system is flawless."),

    (16, "Explain your system architecture.",
     "CrimeNet AI uses a decoupled 5-tier architecture: (1) Client HUD in React 19 and Cytoscape.js; (2) High-throughput ASGI API Gateway in FastAPI; (3) In-Memory Analytical Engines (NetworkX, Scikit-Learn Isolation Forest); (4) Radio/Kinematics Solver; and (5) Persistence Layer (SQLite3 in WAL mode, PBKDF2 vault, SHA-256 Merkle ledger).",
     "Frontend displays the visual map; FastAPI acts as the high-speed router; NetworkX and ML run in memory; SQLite safely stores evidence.",
     "Decoupled client-server model communicating via async HTTPS REST and WebSocket telemetry.",
     "backend/app/main.py, src/App.tsx",
     "Do not claim frontend communicates directly with the database."),

    (17, "Why did you choose React?",
     "React 19 provides component-based reusability, a high-performance virtual DOM, and unidirectional data flow, essential for rendering high-frequency forensic telemetry updates without lagging the browser.",
     "Allows updating individual widgets (like live alerts) without redrawing the entire screen.",
     "Virtual DOM reconciliation minimizes expensive DOM repaints during real-time updates.",
     "package.json, src/App.tsx",
     "React is a UI library, not a full backend framework."),

    (18, "Why TypeScript?",
     "TypeScript introduces static type checking across 48 graph node schemas, API request payloads, and security claims, preventing runtime 'undefined is not a function' crashes during field investigations.",
     "Catches bugs while typing rather than having the application crash during a police operation.",
     "Static compile-time type inference; compiles to clean ECMAScript.",
     "tsconfig.json, src/types.ts",
     "Remember: TypeScript types are stripped at compile time; they have zero runtime overhead."),

    (19, "Why Vite?",
     "Vite 8 leverages native ES modules and a Go-based bundler (esbuild) to provide instant Hot Module Replacement during development and sub-second (417ms) production build rollups.",
     "Replaces old, sluggish build tools like Webpack with near-instant development and production bundling.",
     "Pre-bundles dependencies using esbuild 10-100x faster than Webpack.",
     "vite.config.ts, package.json",
     "Avoid saying Vite is a frontend framework; it is a build tool and dev server."),

    (20, "Why FastAPI?",
     "FastAPI delivers high-throughput asynchronous execution via Starlette and Uvicorn, automatic Pydantic request validation, auto-generated OpenAPI documentation, and seamless native access to Python's scientific ecosystem (NumPy, NetworkX, Scikit-Learn).",
     "Gives the speed of NodeJS with the machine learning power of Python.",
     "ASGI event loop; non-blocking async def endpoints with automatic serialization.",
     "backend/app/main.py",
     "Flask lacks native async support; Django is too bloated for analytical microservices."),

    (21, "Why Python?",
     "Python is the undisputed global standard for scientific computing, graph theory, machine learning, and cryptographic hashing, supported by mature libraries like NetworkX, Scikit-Learn, and NumPy.",
     "Gives immediate access to all verified mathematical and machine learning libraries.",
     "Python 3.14 C-API bindings allow hardware-optimized matrix operations in NumPy and Scikit-Learn.",
     "backend/requirements.txt",
     "Never apologize for Python's interpreted nature; point to C-extensions (NumPy/BLAS) for speed."),

    (22, "Why SQLite?",
     "SQLite3 is a serverless, zero-configuration embedded ACID database. It requires no background daemon, zero port management, and runs directly from a local encrypted file, making it ideal for offline field laptops.",
     "A database that lives inside a single file with zero setup required.",
     "Supports ACID transactions, WAL mode (Write-Ahead Logging) for concurrent reads, and in-memory execution.",
     "backend/crimenet.db, backend/app/main.py",
     "Do not claim SQLite is for 100M concurrent cloud users; justify it for local forensic appliances."),

    (23, "Why NetworkX?",
     "NetworkX provides mathematically rigorous, peer-reviewed implementations of complex graph algorithms including PageRank, Brandes' Betweenness Centrality, and Johnson's elementary cycles in memory.",
     "Provides trusted, scientifically proven graph mathematics out of the box.",
     "Graph adjacency is maintained as nested Python dictionaries: dict-of-dicts-of-dicts for O(1) edge lookups.",
     "backend/app/main.py: lines 340-420",
     "NetworkX is in-memory; for 100M nodes, distributed graph engines like Neo4j would be used."),

    (24, "Why Cytoscape.js?",
     "Cytoscape.js is a hardware-accelerated HTML5 canvas link-analysis library designed specifically for large relational graphs. It supports physics-based force-directed layouts (fcose) without DOM lag.",
     "Renders social network graphs smoothly using canvas instead of heavy webpage elements.",
     "Renders on HTML5 Canvas rather than individual SVG DOM elements, maintaining 60 FPS performance.",
     "src/components/NetworkGraph.tsx",
     "D3.js requires building graph primitives from scratch; Cytoscape gives turn-key link analysis."),

    (25, "Why Mapbox GL?",
     "Mapbox GL uses WebGL for hardware-accelerated vector mapping, allowing real-time rendering of cellular tower coverage circles, GPS coordinates, and ANPR toll radar overlays without frame drops.",
     "Uses the computer's graphics card to draw smooth police map overlays.",
     "WebGL vector tile rendering on GPU canvas.",
     "src/components/MapRadar.tsx",
     "Leaflet uses DOM SVGs which stutter when rendering hundreds of geospatial coordinate rings."),

    (26, "Why Recharts?",
     "Recharts is a declarative React charting library built on SVG elements, providing responsive, interactive visual charts for financial velocity trends and Benford first-digit distributions.",
     "Draws clean, interactive financial charts that adapt to any screen size.",
     "Declarative SVG components integrated cleanly with React state lifecycle.",
     "src/components/VelocityChart.tsx",
     "Recharts is perfect for standard 2D charts, while Cytoscape handles link graphs."),

    (27, "How does frontend communicate with backend?",
     "The frontend communicates with FastAPI via an Axios HTTP REST client using Bearer JWT authentication headers for standard requests, and WebSocket connections for real-time live telemetry streaming.",
     "React sends requests with a secure digital passport (JWT) to FastAPI, which answers with JSON data.",
     "REST APIs over HTTPS; JSON payloads validated via Pydantic; WebSockets over WSS for push telemetry.",
     "src/api.ts, backend/app/main.py",
     "Do not say communication is unencrypted; specify HTTPS with Bearer tokens."),

    (28, "How does the complete request-response cycle work?",
     "User clicks 'Analyze' -> React dispatches Axios GET /api/graph/data -> FastAPI verifies JWT & RBAC -> In-memory NetworkX computes PageRank -> SQLite pulls case metadata -> FastAPI serializes response -> Cytoscape renders graph.",
     "Click button -> Verify user identity -> Run math in RAM -> Fetch records -> Draw interactive visual map.",
     "Client event -> Async HTTP -> Bearer Auth Middleware -> Analytical Controller -> Service Layer -> JSON Response -> Canvas Render.",
     "src/api.ts, backend/app/main.py",
     "Total cycle completes in under 420ms (P99)."),

    (29, "What happens when the backend goes down?",
     "The React frontend implements Axios response interceptors that catch HTTP 500/503 errors and network timeouts, displaying a graceful 'Offline Forensic Mode' notification banner while preserving cached local graph state.",
     "The screen doesn't go blank; it shows an offline status bar and keeps the current case map visible.",
     "Axios interceptor handles rejected promises; UI renders fallback Alert banner without crashing.",
     "src/api.ts, src/App.tsx",
     "Always demonstrate robust error handling on the frontend."),

    (30, "How would you scale this architecture to 50 million records?",
     "To scale to 50 million records: (1) Replace SQLite with PostgreSQL or TimescaleDB with partition indexing; (2) Migrate in-memory NetworkX to a distributed Neo4j or Amazon Neptune cluster; (3) Ingest streaming data via Apache Kafka; and (4) Decouple ML inference into asynchronous Celery/Redis worker pools.",
     "Move from a local laptop file database to cloud-scale database clusters and streaming queues.",
     "SQLite -> PostgreSQL (pg_partman) -> Neo4j Enterprise (Cypher cluster) -> Kafka streams -> Celery/Triton inference.",
     "backend/app/main.py",
     "Never say you need Kubernetes for an MVP; explain the phased scaling path."),

    (31, "Why not PostgreSQL initially?",
     "PostgreSQL requires background daemon installation, user credential configuration, and port listening, which complicates deployment on standalone, air-gapped forensic laptops in the field. SQLite delivers zero-latency embedded queries with zero setup.",
     "SQLite lives in a single file; PostgreSQL requires running a database server service.",
     "Zero socket overhead for embedded forensic appliances.",
     "backend/crimenet.db",
     "Postgres is the obvious production migration target; justify SQLite for the prototype."),

    (32, "Why not MongoDB?",
     "MongoDB is a document store that lacks native graph traversal algorithms, lacks ACID foreign key integrity between cases and evidence items, and requires complex aggregations for relational link analysis.",
     "MongoDB stores documents, but organized crime is all about relationships and strict evidence links.",
     "Document store lacks native graph traversal pointers; MongoDB $lookup joins are slow and complex.",
     "backend/app/main.py",
     "Document databases are poor choices for highly connected relational networks."),

    (33, "Why not Neo4j initially?",
     "Neo4j requires significant Java Virtual Machine (JVM) memory overhead (2-4 GB minimum RAM) and complex Cypher query drivers. NetworkX operates purely in Python memory, allowing instant mathematical interoperability with NumPy and Scikit-Learn with zero JVM overhead.",
     "NetworkX runs in pure Python; Neo4j requires a heavy Java server running in the background.",
     "Eliminates Cypher bridge latency and JVM heap allocation for local 48-node analysis.",
     "backend/app/main.py",
     "Acknowledge that for >1M nodes, Neo4j becomes necessary."),

    (34, "Why not microservices initially?",
     "Microservices introduce distributed network latency, RPC serialization overhead, container orchestration complexity, and distributed transaction issues (two-phase commits) that are counterproductive for an MVP forensic appliance.",
     "Building 10 separate microservices for a prototype creates massive networking headaches without any benefit.",
     "Monolithic decoupled architecture maximizes single-node throughput and simplifies debugging.",
     "backend/app/main.py",
     "Premature microservice decomposition is a recognized anti-pattern in software engineering."),

    (35, "What would your production architecture look like?",
     "Production architecture: CloudFlare CDN/WAF -> Kubernetes ingress -> Load-balanced FastAPI container pods -> Distributed Neo4j graph cluster -> TimescaleDB for time-series telecom telemetry -> Kafka message broker -> Redis cache -> Celery ML workers with GPU acceleration.",
     "A cloud cluster where data streaming, graph storage, and machine learning run on dedicated auto-scaling servers.",
     "Fully decoupled event-driven microservices architecture on AWS or Azure Government Cloud.",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Draw the cloud architecture clearly on the whiteboard if asked."),

    (36, "What is a knowledge graph?",
     "A knowledge graph is a network of real-world entities (nodes) connected by semantically typed relationships (edges), representing complex domain knowledge in a graph data model.",
     "A web of dots (people, phones, banks) connected by labeled lines (called, transferred, met).",
     "Formal definition: G = (V, E, L_v, L_e) with vertex and edge labeling functions.",
     "backend/app/main.py: lines 300-340",
     "It is not just a chart; it is a mathematical graph data structure."),

    (37, "Why did you use a graph?",
     "Because organized crime syndicates operate as networks, not isolated database rows. Graphs allow constant-time relationship traversal, multi-hop proxy discovery, and topological centrality calculations.",
     "To catch criminals who hide behind intermediaries, you must follow the connections, which graphs do natively.",
     "O(1) adjacency pointer lookups vs O(N) relational table joins.",
     "backend/app/main.py",
     "Relational tables fail when tracing multi-hop connections."),

    (38, "What is a node?",
     "A node (vertex) represents a distinct entity in the forensic domain, such as a suspect, a bank account, a burner phone, or a toll plaza.",
     "The dots on the map representing real-world objects or people.",
     "Vertex v in V with associated property dictionary (id, type, label, metadata).",
     "backend/app/main.py: line 310",
     "Nodes hold properties; edges define connections."),

    (39, "What is an edge?",
     "An edge (arc) represents a directed relationship or interaction between two nodes, such as a phone call, a bank wire transfer, or co-location.",
     "The lines connecting the dots that show who talked to whom or who paid whom.",
     "Directed pair (u, v) in E with properties (weight, relation_type, timestamp).",
     "backend/app/main.py: line 320",
     "Edges in CrimeNet are directed; direction matters!"),

    (40, "What types of nodes exist in CrimeNet?",
     "CrimeNet AI models 6 node types: Person (Suspects/Kingpins), Account (Bank/Hawala), Phone (IMEI/MSISDN), Vehicle (Couriers), Location (Cell towers/Tolls), and Event (Raids/Meetings).",
     "The nouns: people, phones, bank accounts, cars, towers, and events.",
     "Heterogeneous node schema with strict typing in TypeScript and Pydantic.",
     "src/types.ts, backend/app/main.py",
     "Ensure you can list all 6 node types quickly."),

    (41, "What types of relationships exist?",
     "Five core relationship types: TRANSACTED_WITH (money transfers), CALLED (telecom logs), ASSOCIATED_WITH (co-conspirators), CO_LOCATED (same cell tower/location), and TRAVELLED_TO (toll crossings).",
     "The verbs: paid, called, associated, met, traveled.",
     "Typed directed edges with numerical weights representing interaction strength.",
     "backend/app/main.py: lines 320-335",
     "Edges represent interactions, not assumptions."),

    (42, "Why is graph representation useful for investigations?",
     "It exposes hidden multi-hop proxy chains, detects circular money laundering loops, highlights influential kingpins who never make direct contact, and allows visual link exploration on an interactive canvas.",
     "It turns invisible connections spread across thousands of spreadsheet rows into an obvious visual pattern.",
     "Enables topological algorithms: PageRank, Betweenness Centrality, Dijkstra, and Johnson's cycles.",
     "backend/app/main.py",
     "Graphs make indirect connections obvious at a glance."),

    (43, "What is graph traversal?",
     "Graph traversal is the algorithmic process of visiting each vertex in a graph by following adjacent edges, typically implemented via Breadth-First Search (BFS) or Depth-First Search (DFS).",
     "Walking from dot to dot along the lines to explore who is connected to whom.",
     "BFS explores layer by layer (O(V+E)); DFS explores deep along branch paths.",
     "backend/app/main.py: lines 450-500",
     "Traversal is the foundation for all graph queries."),

    (44, "What is a hop?",
     "A hop is a single step across an edge from one node to an immediately adjacent neighbor.",
     "One step along a connecting line.",
     "Edge transition: u -> v is 1 hop; u -> v -> w is 2 hops.",
     "backend/app/main.py",
     "Hops measure network distance, not geographical distance."),

    (45, "What is a 5-hop traversal?",
     "A 5-hop traversal is a graph search bounded at a depth of 5 edges from the source entity, discovering all entities separated by up to 4 intermediaries.",
     "Finding friends of friends of friends of friends of friends.",
     "Bounded BFS: depth <= 5. Essential for uncovering insulated syndicate bosses.",
     "backend/app/main.py: lines 480-510",
     "Unbounded traversal causes combinatorial explosion; always bound depth!"),

    (46, "How do you find indirect relationships?",
     "We find indirect relationships using Breadth-First Search (BFS) bounded at 5 hops, identifying intermediary proxy cut-out nodes that connect two targets who have no direct edge between them.",
     "By searching layer by layer to see who acts as the mutual contact between two suspects.",
     "Traces predecessor pointers in the BFS search tree from target back to source.",
     "backend/app/main.py: lines 450-510",
     "Direct calls are rare in syndicates; indirect paths reveal the conspiracy."),

    (47, "Why not represent everything as tables?",
     "Because finding a 5-hop path in SQL requires 5 table self-joins on millions of rows, resulting in exponential O(N^k) query slowdown and potential database lockouts.",
     "Joining huge tables multiple times brings databases to a crawl; graphs navigate connections instantly.",
     "Relational JOIN complexity O(N^k) vs Graph pointer chasing O(deg(v)^k).",
     "backend/app/main.py",
     "Tables are great for accounting; graphs are essential for relationships."),

    (48, "What is a directed graph?",
     "A directed graph (digraph) is a graph where edges have an orientation from a source vertex to a target vertex: (u, v) is not equivalent to (v, u).",
     "A one-way street network: Phone A calling Phone B is an outgoing call from A to B.",
     "Adjacency matrix is asymmetric: A[u,v] != A[v,u].",
     "backend/app/main.py: nx.DiGraph()",
     "Transactions and calls are always directed; using an undirected graph loses causality."),

    (49, "What is a weighted graph?",
     "A weighted graph assigns a numerical value (weight) to each edge representing the intensity, frequency, or volume of the relationship.",
     "A map where some roads have heavy traffic (many calls) and others have light traffic (one call).",
     "G = (V, E, W), where W: E -> R+ assigns non-negative weights.",
     "backend/app/main.py: line 325",
     "Weights allow ranking which connections are strong vs coincidental."),

    (50, "How do you calculate edge weights?",
     "We compute composite edge weights using normalized linear combination: W(u,v) = 0.4 * norm(Call_Count) + 0.3 * norm(Duration) + 0.3 * norm(Transaction_Amount).",
     "We blend call frequency, call length, and money transferred into a single score from 0 to 1.",
     "W = alpha * (C/C_max) + beta * (D/D_max) + gamma * (A/A_max), with alpha+beta+gamma=1.",
     "backend/app/main.py: lines 320-340",
     "Remember: In shortest path algorithms, high weights must be inverted so strong links have short distances!"),

    (51, "How do you handle disconnected nodes?",
     "Disconnected nodes (isolated singletons) are preserved in the vertex set V with degree 0. In PageRank, the random teleportation term (1 - d)/N ensures every node receives a valid baseline authority score even with zero links.",
     "Islands in the network: they don't break the math because PageRank allows random jumps.",
     "Handling: G.add_node(v); PageRank damping factor guarantees convergence on disconnected components.",
     "backend/app/main.py: nx.pagerank()",
     "Never drop disconnected nodes; an isolated burner phone might become active later."),

    (52, "How do you handle duplicate entities?",
     "We apply Entity Resolution: during ingestion, records with identical phone numbers, IMEIs, or PAN tax IDs are merged into a single canonical entity ID with aliased identifiers.",
     "If the same person appears under two nicknames with the same phone number, we combine them into one dot.",
     "Canonical mapping table: alias_map[identifier] = canonical_id.",
     "backend/app/main.py: lines 280-310",
     "Duplicate entities split centrality scores, hiding the true kingpin."),

    (53, "How do you handle missing relationships?",
     "Missing relationships are handled via Link Prediction algorithms (Adamic-Adar index, Jaccard coefficient of common neighbors) to compute probability scores for unobserved connections.",
     "If two suspects share 10 mutual contacts, they probably know each other even if we haven't intercepted a direct call yet.",
     "Adamic-Adar score: sum_{z in N(u) cap N(v)} 1 / log(deg(z)).",
     "backend/app/main.py: lines 580-620",
     "Predicted links are strictly marked as 'Probable Link' in the UI."),

    (54, "How does graph size affect performance?",
     "As graph size grows, memory consumption scales as O(V + E). In-memory NetworkX handles up to 100,000 nodes in under 500 MB RAM. Beyond 1 million nodes, RAM exhausts, requiring migration to disk-backed graph databases like Neo4j.",
     "Our 48-node prototype runs instantly in RAM; for millions of nodes, you need distributed database clusters.",
     "Memory: dict-of-dicts takes ~1 KB per node. At 10M nodes, memory exceeds 10 GB.",
     "backend/app/main.py",
     "Know your scale limits: in-memory is fast for cases; distributed is needed for national databases."),

    (55, "What is graph density and what is CrimeNet's density?",
     "Graph density measures the ratio of actual edges to the maximum possible edges: D = |E| / (|V| * (|V| - 1)). In CrimeNet's 48-node syndicate graph with 112 directed edges, density is D = 112 / (48 * 47) = 0.0496 (~5.0%). Real criminal networks are characteristically sparse to prevent mass detection.",
     "Only 5% of all possible connections exist because criminals keep communications tight and compartmentalized.",
     "D = 112 / 2256 = 0.0496. Sparse networks match real criminal tradecraft.",
     "backend/app/main.py: lines 340-360",
     "Dense networks (>50% density) are typical of social networks, not secretive criminal syndicates."),

    (56, "What is PageRank?",
     "PageRank is a link-analysis algorithm developed by Google that measures the structural authority of each node in a graph based on the quantity and quality of incoming edges.",
     "A voting system where a vote from someone powerful carries vastly more weight than a vote from an unknown person.",
     "Principal eigenvector of the Google stochastic transition matrix.",
     "backend/app/main.py: lines 340-380",
     "PageRank is not just counting links; it evaluates who is linking to you."),

    (57, "How does PageRank work?",
     "It models a random surfer who traverses edges with probability d and teleports to a random node with probability (1 - d). Nodes accumulate rank based on the rank of nodes pointing to them divided by their out-degree.",
     "Influence flows across the network like water until it pools at the most authoritative hubs.",
     "Iterative stationary distribution solver: p_{k+1} = (1-d)/N + d * M * p_k.",
     "backend/app/main.py: lines 345-365",
     "Converges via Power Iteration in 16 iterations in CrimeNet."),

    (58, "What is the PageRank formula?",
     "PR(u) = (1 - d) / N + d * sum_{v in B_u} (PR(v) / L(v)), where B_u is the set of vertices linking to u, L(v) is the out-degree of v, N is total nodes, and d is the damping factor.",
     "Your rank = baseline teleport chance + 85% of the rank shared by everyone who points to you.",
     "PR(u) = (1 - d)/N + d * sum_{v in B_u} (PR(v) / L(v)). Solved as an eigenvector problem.",
     "backend/app/main.py: line 350",
     "Memorize this formula; it is frequently requested on whiteboards!"),

    (59, "What is the damping factor?",
     "The damping factor (d) represents the probability that the random surfer continues following graph edges rather than jumping randomly to a new vertex.",
     "The chance that an investigator follows an actual phone link (85%) versus picking a random suspect (15%).",
     "Parameter d in [0, 1]. Ensures the transition matrix is irreducible and aperiodic.",
     "backend/app/main.py: alpha=0.85",
     "Without damping (d=1), rank gets trapped in dead ends and spider traps."),

    (60, "Why did you use 0.85?",
     "0.85 is the scientifically established standard established by Page and Brin, balancing rapid numerical convergence (around 15-20 iterations) with faithful structural link modeling while preventing sink traps.",
     "It is the industry-standard balance that gives accurate results without getting stuck.",
     "Guarantees the spectral radius of the transition matrix is bounded, ensuring convergence by the Perron-Frobenius theorem.",
     "backend/app/main.py: alpha=0.85",
     "Using 0.85 is backed by decades of peer-reviewed graph literature."),

    (61, "What does high PageRank mean?",
     "High PageRank means a node receives links from other nodes that themselves possess high structural authority and connectivity in the network.",
     "It means the most influential people in the syndicate report to this person.",
     "Node u has a high coordinate in the principal eigenvector of the graph transition matrix.",
     "backend/app/main.py: lines 340-380",
     "High PageRank does NOT mean high link count; it means high-quality links."),

    (62, "Why is PageRank useful in CrimeNet?",
     "In syndicates, the boss never calls street-level couriers. He only communicates with a few lieutenants. Because those lieutenants have massive operational connectivity, their endorsements funnel authority directly into the boss, making his PageRank the highest in the syndicate (0.081).",
     "It cuts through the smoke and mirrors to spot the boss hiding behind layers of cut-outs.",
     "Exposes insulated hierarchal leaders without requiring direct evidence of street crimes.",
     "backend/app/main.py: lines 350-380",
     "Highlight that Arjun Mehta has highest PageRank (0.081) despite low direct link count."),

    (63, "Does high PageRank mean a person is criminal?",
     "NO. High PageRank indicates structural network authority; it does NOT determine criminal guilt. A legitimate defense lawyer or bank manager communicating with many suspects would also have high PageRank. Human corroboration is mandatory.",
     "Being a central figure in a network doesn't make you guilty—a lawyer or company CEO also looks central.",
     "Mathematical centrality is neutral; intent and criminal acts must be proven by evidence.",
     "backend/app/main.py",
     "CRITICAL TRAP: Never claim PageRank proves criminal guilt!"),

    (64, "What happens if the graph changes?",
     "When new edges or nodes are ingested, NetworkX re-runs Power Iteration. Because CrimeNet operates on 48 nodes, re-convergence takes less than 5 milliseconds, instantly updating the leaderboard.",
     "When a new phone call is intercepted, the math updates in the blink of an eye.",
     "Incremental power iteration or full re-computation in O(k * E) where k is iterations.",
     "backend/app/main.py: startup_event()",
     "At 48 nodes, full re-computation is faster than complex dynamic graph maintenance."),

    (65, "What is the computational complexity of PageRank?",
     "PageRank computed via Power Iteration has a time complexity of O(k * (V + E)), where k is the number of iterations until convergence (typically 15-30), V is vertices, and E is edges.",
     "It takes about 16 passes over all the connections in the network.",
     "Each iteration performs a matrix-vector multiplication: O(V + E) for sparse graphs.",
     "backend/app/main.py: tol=1e-6",
     "Linear with respect to edges: highly efficient for sparse networks."),

    (66, "PageRank vs Degree Centrality?",
     "Degree Centrality simply counts direct links: (In + Out) / (N - 1), identifying noisy field couriers or call centers. PageRank evaluates link quality, identifying the insulated boss who has few links from powerful lieutenants.",
     "Degree = Most active person. PageRank = Most powerful boss.",
     "Degree is local O(1); PageRank is global O(k * (V+E)).",
     "backend/app/main.py: lines 340-420",
     "A call-center bot has high degree but near-zero PageRank."),

    (67, "PageRank vs Betweenness Centrality?",
     "PageRank identifies hierarchical authority (the kingpin boss); Betweenness Centrality identifies information bottlenecks and bridges (the Hawala money courier or broker).",
     "PageRank finds the general; Betweenness finds the messenger running between rival camps.",
     "PageRank uses eigenvector random walks; Betweenness calculates shortest-path fractions.",
     "backend/app/main.py: lines 340-420",
     "Duality: Mehta has highest PageRank (0.081); Rafiq has highest Betweenness (0.142)."),

    (68, "What is Betweenness Centrality and what is its formula?",
     "Betweenness Centrality measures the extent to which a vertex lies on the shortest paths between other vertices: g(v) = sum_{s != v != t} (sigma_{st}(v) / sigma_{st}), where sigma_{st} is total shortest paths from s to t and sigma_{st}(v) is those passing through v.",
     "How often a person acts as the essential bridge between any two other people.",
     "g(v) = sum_{s != v != t} (sigma_{st}(v) / sigma_{st}). Normalized by 2 / ((N-1)(N-2)).",
     "backend/app/main.py: lines 385-420",
     "Memorize this formula; it is a standard viva question!"),

    (69, "Why did you use Betweenness Centrality?",
     "To identify the financial brokers, couriers, and cut-outs who connect separated criminal cliques. Severing high-betweenness nodes shatters syndicate communication and stops money laundering.",
     "To find the key bridge that, if arrested, stops the two gangs from talking to each other.",
     "Locates structural articulation points and critical bridges in the graph topology.",
     "backend/app/main.py: lines 390-410",
     "Removing high-betweenness nodes maximizes network disruption."),

    (70, "What does high betweenness mean with a real example?",
     "It means a node controls the flow of information or funds between groups. In CrimeNet, Hawala broker Mohammed Rafiq has high betweenness (0.142) because all funds flowing from domestic mule accounts to offshore shell companies must pass through his escrow ledger.",
     "Mohammed Rafiq is the only bridge between the street gangs in Mumbai and the money accounts in Dubai.",
     "High pair-dependency accumulation: delta_{s*}(Rafiq) is maximal across all pairs.",
     "backend/app/main.py: lines 395-415",
     "Point to Mohammed Rafiq on the live graph as the concrete example."),

    (71, "What is Brandes' Algorithm and its complexity?",
     "Ulrik Brandes' algorithm (2001) computes Betweenness Centrality for all vertices by combining BFS/Dijkstra shortest-path trees with a backward dependency accumulation pass, reducing complexity from O(V^3) to O(V * E) for unweighted graphs (or O(V*E + V^2 log V) for weighted graphs).",
     "A clever algorithm that calculates shortest paths and dependencies in a single backward sweep instead of checking every pair from scratch.",
     "Computes pair dependencies delta_{s*}(v) recursively in reverse BFS order.",
     "backend/app/main.py: nx.betweenness_centrality()",
     "Brandes' algorithm made betweenness practical for large real-world networks."),

    (72, "Can high betweenness prove criminal activity?",
     "NO. High betweenness proves network centrality and bridge positioning, not criminal conspiracy. A legitimate court receiver, mutual bank clerk, or delivery driver could exhibit high betweenness. Human forensic review is mandatory.",
     "A delivery driver or postal worker also connects lots of separated people.",
     "Centrality is a topological property, not a legal verdict.",
     "backend/app/main.py",
     "Never equate mathematical metrics with judicial guilt."),

    (73, "What is Closeness Centrality?",
     "Closeness Centrality measures how close a node is to all other nodes in the network: C(u) = (N - 1) / sum_{v != u} dist(u, v). High closeness indicates an operative who can rapidly disseminate orders to the entire syndicate.",
     "How few steps it takes for a person to reach everyone else in the gang.",
     "Reciprocal of average shortest-path distance.",
     "backend/app/main.py: lines 425-440",
     "Useful for identifying operational coordinators who broadcast orders."),

    (74, "What is Eigenvector Centrality?",
     "Eigenvector Centrality assigns relative scores to all nodes based on the principle that connections to high-scoring nodes contribute more to the score of the node: lambda * x = A * x, where A is the adjacency matrix.",
     "PageRank's predecessor: you are important if you are connected to important people.",
     "Principal eigenvector of the un-damped adjacency matrix.",
     "backend/app/main.py",
     "PageRank adds damping (d=0.85) to fix convergence issues in directed graphs."),

    (75, "How do centralities guide investigative resource allocation?",
     "Investigators allocate wiretap and surveillance warrants based on centrality roles: high PageRank entities (Kingpins) receive legal wiretaps; high Betweenness entities (Brokers) receive financial freeze orders; high Degree entities (Couriers) receive physical checkpoint intercepts.",
     "Arrest the courier on the road, freeze the broker's bank accounts, and put wiretaps on the boss.",
     "Maps mathematical centrality roles to proportional operational tactics.",
     "backend/app/main.py",
     "Shows real-world forensic applicability of graph math."),

    (76, "What is Dijkstra's algorithm?",
     "Dijkstra's algorithm is a greedy graph search algorithm that solves the single-source shortest path problem for weighted graphs with non-negative edge weights in O((V + E) log V) time.",
     "It finds the fastest route between two people on the network map.",
     "Maintains min-heap priority queue; relaxes outgoing edges: dist[v] = min(dist[v], dist[u] + w(u,v)).",
     "backend/app/main.py: nx.shortest_path()",
     "Requires non-negative edge weights."),

    (77, "Why use Dijkstra in CrimeNet?",
     "To trace the most direct, strongest operational communication path between two suspects separated by multiple cut-outs.",
     "To see the exact chain of phone calls or money transfers connecting a street runner to the boss.",
     "Reciprocal edge weights (1 / Weight) allow Dijkstra to find the path of highest relational strength.",
     "backend/app/main.py: lines 450-480",
     "Invert weights so high-frequency links have low traversal cost!"),

    (78, "How does Dijkstra work step by step?",
     "1. Set dist[source]=0, all others inf. 2. Push source to min-heap. 3. Pop node u with smallest dist. 4. For each neighbor v, if dist[u] + w(u,v) < dist[v], update dist[v] and push to heap. 5. Mark u visited. 6. Repeat until target visited.",
     "Start at suspect A with distance 0, explore his closest friends first, and keep expanding until you reach suspect B.",
     "Greedy relaxation invariant: visited nodes have final shortest distances.",
     "backend/app/main.py: lines 460-490",
     "Greedy choice property guarantees optimality."),

    (79, "What is Dijkstra's time complexity?",
     "Using a min-binary heap, time complexity is O((V + E) log V). With a Fibonacci heap, it reduces to O(E + V log V).",
     "It scales very fast: proportional to connections times log of people.",
     "O(|E| + |V| log |V|) with Fibonacci heap; O((|V| + |E|) log |V|) with standard binary heap.",
     "backend/app/main.py",
     "Runs in sub-millisecond time on our 48-node graph."),

    (80, "What assumptions does Dijkstra make?",
     "It assumes all edge weights are strictly non-negative: w(u, v) >= 0. If negative weights exist, Dijkstra can declare a node visited prematurely, producing incorrect shortest paths.",
     "All travel costs must be zero or positive; you can't have negative distance.",
     "Weight function W: E -> [0, inf).",
     "backend/app/main.py",
     "If negative weights exist, Bellman-Ford O(V*E) must be used."),

    (81, "What is A* search?",
     "A* is a best-first heuristic search algorithm that computes the shortest path by evaluating nodes using f(n) = g(n) + h(n), where g(n) is exact cost from start, and h(n) is estimated cost to goal.",
     "Dijkstra with a compass pointing towards the target so it doesn't search backwards.",
     "f(n) = g(n) + h(n). Guaranteed optimal if h(n) is admissible.",
     "backend/app/main.py: lines 520-560",
     "Combines Dijkstra's completeness with Greedy Best-First Search speed."),

    (82, "What is the A* formula?",
     "f(n) = g(n) + h(n), where g(n) is the exact accumulated path cost from the start node to current node n, and h(n) is the heuristic estimated cost from node n to the destination target.",
     "Total expected cost = distance traveled so far + estimated distance remaining to goal.",
     "f(n) estimates total cost of cheapest solution through node n.",
     "backend/app/main.py: line 530",
     "Memorize this formula for viva!"),

    (83, "What is a heuristic?",
     "A heuristic is a problem-specific function h(n) that estimates the remaining cost to reach the goal from node n without performing a full search.",
     "An educated guess of how far you still have to go.",
     "Function h: V -> R+. For spatial graphs, Euclidean or Haversine distance is used.",
     "backend/app/main.py: lines 535-550",
     "Must be computationally fast to calculate."),

    (84, "Why use A* over Dijkstra?",
     "A* explores significantly fewer vertices than Dijkstra by pruning search directions that move away from the destination, making it much faster on large geospatial highway camera networks.",
     "Dijkstra searches in a circle in all directions; A* aims straight at the destination camera.",
     "Reduces effective branching factor b* towards 1.0.",
     "backend/app/main.py",
     "Essential for real-time tracking across 10,000 highway toll cameras."),

    (85, "What makes a heuristic admissible?",
     "A heuristic is admissible if it never overestimates the true remaining cost to the goal: h(n) <= h*(n) for all nodes n, where h*(n) is the true optimal cost.",
     "Your guess must always be optimistic or exact; you can never guess higher than reality.",
     "Underestimation guarantee: h(n) <= dist_optimal(n, goal).",
     "backend/app/main.py: lines 540-555",
     "Straight-line Euclidean distance is always admissible because it is the shortest possible physical distance."),

    (86, "What happens with a bad or inadmissible heuristic?",
     "If h(n) is inadmissible (overestimates cost), A* loses its mathematical guarantee of optimality and may return a suboptimal path. If h(n) = 0, A* degrades to standard Dijkstra.",
     "If your compass lies, you might take a longer detour. If your compass is broken (0), you search in all directions like Dijkstra.",
     "Overestimation violates tree pruning bounds.",
     "backend/app/main.py",
     "Inadmissible heuristics trade optimality for search speed."),

    (87, "Can A* guarantee the shortest path?",
     "YES, provided the heuristic is admissible on trees, or consistent (monotonic: h(n) <= c(n, a, n') + h(n')) on general graphs.",
     "Yes, as long as your guess is optimistic, A* is mathematically guaranteed to find the true shortest path.",
     "Proven by Hart, Nilsson, and Raphael (1968).",
     "backend/app/main.py",
     "Consistency also guarantees that no visited node needs to be re-opened."),

    (88, "Can Dijkstra work with negative edges?",
     "NO. Dijkstra cannot work with negative edge weights because negative edges violate the greedy choice property, potentially causing infinite loops in negative cycles or returning incorrect paths.",
     "No, negative costs break the rule that visited nodes are finalized.",
     "Requires non-negative weights; use Bellman-Ford O(V*E) for graphs with negative weights.",
     "backend/app/main.py",
     "Standard interview trap question!"),

    (89, "Why detect graph cycles?",
     "To uncover circular money laundering and Hawala smurfing schemes, where illicit funds are transferred through multiple intermediary mule accounts and returned back to the originator.",
     "To catch criminals who move money in circles to make dirty cash look like clean business.",
     "Uncovers cyclic topologies in directed financial transaction graphs.",
     "backend/app/main.py: lines 1150-1210",
     "Cycles indicate circular flow of funds."),

    (90, "What is a graph cycle?",
     "A directed cycle is a non-empty directed path in which the first and last vertices are identical: v0 -> v1 -> v2 -> ... -> v0, with no other repeated vertices.",
     "A closed loop where following the arrows brings you right back to where you started.",
     "Elementary cycle: closed directed walk with distinct intermediate vertices.",
     "backend/app/main.py: line 1155",
     "Simple cycle = Elementary cycle."),

    (91, "Give an example of a Hawala transaction cycle.",
     "Suspect Mehta Shell wires ₹48,500 to Mule Account 1 (Bandra) -> Mule 1 wires ₹47,200 to Mule Account 2 (Andheri) -> Mule 2 wires ₹46,000 to an offshore escrow -> Offshore escrow transfers settlement funds back to Mehta Shell.",
     "Mehta sends ₹48k to Mule A, who sends to Mule B, who sends to Dubai, who sends it right back to Mehta's company.",
     "Closed directed loop spanning 4 accounts within 48 hours.",
     "backend/app/main.py: lines 1160-1190",
     "Matches classic placement, layering, and integration laundering stages."),

    (92, "How can cycles indicate suspicious behavior?",
     "Legitimate commerce flows in linear supply chains (Customer -> Retailer -> Wholesaler -> Manufacturer). Circular fund flows serve no commercial purpose other than layering financial trails to obscure origin.",
     "In real business, customers don't get their own money back through 4 shell companies 2 days later.",
     "Violates economic rational utility; characteristic signature of Hawala smurfing.",
     "backend/app/main.py",
     "Indicates artificial layering of transactions."),

    (93, "What algorithm do you use for cycle detection?",
     "We use Donald B. Johnson's Elementary Cycles Algorithm (1975), implemented in NetworkX as `nx.simple_cycles()`.",
     "Johnson's algorithm.",
     "Decomposes graph into Strongly Connected Components (SCCs) via Tarjan's algorithm and applies DFS with unblocking.",
     "backend/app/main.py: line 1150",
     "Scientifically verified cycle detection algorithm."),

    (94, "What is Johnson's algorithm time complexity?",
     "Johnson's algorithm has a time complexity of O((V + E)(C + 1)), where V is vertices, E is edges, and C is the total number of elementary cycles in the graph.",
     "Time is proportional to connections multiplied by the number of loops found.",
     "Optimal complexity: time per cycle is bounded by O(V + E).",
     "backend/app/main.py: line 1150",
     "Outperforms naive Tarjan DFS which can explore exponential paths."),

    (95, "Does a cycle prove money laundering?",
     "NO. A cycle proves circular topological structure; it does NOT prove money laundering. Legitimate business refunds, escrow reversals, or bilateral currency settlements also form cycles. Human forensic corroboration is mandatory.",
     "A loop is suspicious, but it could be a store refund or escrow release. An officer must check the bank slips.",
     "Topological pattern != Legal proof of criminal intent.",
     "backend/app/main.py",
     "CRITICAL TRAP: Never state that a graph cycle alone proves criminal guilt in court!"),

    (96, "How would you reduce false positives from cycle detection?",
     "By applying four forensic filters: (1) Time Window: cycle must complete within 72 hours; (2) Amount Preservation: output amount must match input minus <= 5% commission; (3) Tax Diversity: loop must span >= 3 distinct PAN IDs; (4) Rapid Velocity: transactions execute in minutes rather than quarterly billing intervals.",
     "Check that the money moved within 2 days, the amount didn't change much, and multiple tax IDs were used.",
     "Filters by delta_t <= 72h, delta_amount <= 0.05, len(unique_pan) >= 3.",
     "backend/app/main.py: lines 1170-1215",
     "Dramatically lowers false alarm rates."),

    (97, "What is Tarjan's Strongly Connected Components (SCC) algorithm?",
     "Tarjan's algorithm finds all Strongly Connected Components in a directed graph in linear time O(V + E) using depth-first search, maintaining low-link values and a visitation stack.",
     "It groups together all the clusters where every person can reach every other person.",
     "Linear time O(|V| + |E|). Used as a pre-processing step in Johnson's cycle algorithm.",
     "backend/app/main.py",
     "Cycles can only exist within Strongly Connected Components!"),

    (98, "Why decompose into SCCs before finding cycles?",
     "Because edges connecting two different SCCs can never participate in a cycle. Decomposing into SCCs eliminates unproductive search space, guaranteeing that Johnson's algorithm only searches subgraphs that can contain cycles.",
     "You throw away all the one-way dead ends before searching for circles.",
     "Prunes cross-component edges; restricts DFS search to non-trivial components with |V| > 1.",
     "backend/app/main.py",
     "Huge performance optimization for large networks."),

    (99, "What is the unblocking mechanism in Johnson's algorithm?",
     "Johnson maintains a boolean blocked map and a dictionary of blocked nodes. When a node is explored, it is blocked to prevent duplicate path exploration; it is only unblocked if a cycle is successfully closed, guaranteeing zero wasted search steps.",
     "It locks a path while walking down it, and only unlocks it if that path actually formed a circle.",
     "Guarantees that every path explored either finds an elementary cycle or terminates without redundant backtracking.",
     "backend/app/main.py: line 1150",
     "Key theoretical insight of Donald Johnson's 1975 paper."),

    (100, "What is Bellman-Ford algorithm and when is it needed?",
     "Bellman-Ford solves the single-source shortest path problem in O(V * E) time. Unlike Dijkstra, it handles graphs with negative edge weights and detects negative weight cycles.",
     "A slower shortest path algorithm that can safely handle negative numbers and detect infinite discount loops.",
     "Relaxes all |E| edges |V| - 1 times. If a further relaxation reduces distance, a negative cycle exists.",
     "backend/app/main.py",
     "Needed only if financial ledgers assign negative costs to cash rebates.")
]

print(f"Loaded {len(BATCH1_QUESTIONS)} questions in Batch 1.")
