# questions_batch3.py: Questions 201 to 300
# Covers: Cross-Validation, Unsupervised Traps, Cybersecurity, Merkle Trees

BATCH3_QUESTIONS = [
    (201, "What is ROC-AUC?",
     "ROC-AUC (Area Under the Receiver Operating Characteristic Curve) measures the probability that the classifier ranks a randomly chosen positive instance higher than a randomly chosen negative instance across all thresholds.",
     "A score from 0 to 1 that tells you how well the model separates anomalies from normal data, regardless of what cutoff threshold you pick.",
     "Integrates TPR vs FPR across threshold tau in [-inf, inf].",
     "backend/data/ncfb_2026_cv_results.json",
     "Our score is 0.998."),

    (202, "What is a confusion matrix?",
     "A confusion matrix is a specific 2x2 contingency table that visualizes classifier performance by comparing true target classes against predicted classes: rows represent true classes; columns represent predicted classes.",
     "A 4-box table showing: caught criminals (TP), false alarms (FP), missed criminals (FN), and correctly cleared citizens (TN).",
     "Contingency matrix [[TN, FP], [FN, TP]].",
     "backend/data/ncfb_2026_cv_results.json",
     "The foundation for all derived metrics."),

    (203, "What is TP (True Positive)?",
     "A True Positive is a record where an actual forensic anomaly was correctly predicted as an anomaly by the model. In CrimeNet, TP = 464.",
     "A real criminal that the system caught.",
     "y_true = -1 (anomaly) and y_pred = -1.",
     "backend/data/ncfb_2026_cv_results.json",
     "High TP means strong detection."),

    (204, "What is FP (False Positive)?",
     "A False Positive is an innocent, normal transaction incorrectly flagged as an anomaly by the model. In CrimeNet, FP = 16.",
     "A false alarm: an innocent transaction flagged as suspicious.",
     "y_true = +1 (normal) and y_pred = -1.",
     "backend/data/ncfb_2026_cv_results.json",
     "Low FP (16) prevents investigator fatigue."),

    (205, "What is FN (False Negative)?",
     "A False Negative is an actual criminal anomaly that the model failed to detect, classifying it as normal. In CrimeNet, FN = 16.",
     "A criminal that slipped through undetected.",
     "y_true = -1 (anomaly) and y_pred = +1.",
     "backend/data/ncfb_2026_cv_results.json",
     "Low FN (16) means high investigative coverage."),

    (206, "What is TN (True Negative)?",
     "A True Negative is a normal inlier transaction correctly identified as normal by the model. In CrimeNet, TN = 9,504.",
     "An innocent person correctly ignored by the system.",
     "y_true = +1 (normal) and y_pred = +1.",
     "backend/data/ncfb_2026_cv_results.json",
     "Accounts for the vast majority of daily banking traffic."),

    (207, "How do you calculate precision from your confusion matrix?",
     "Precision = TP / (TP + FP) = 464 / (464 + 16) = 464 / 480 = 0.96666... = 96.67% (96.7%).",
     "464 real criminals caught divided by 480 total alarms raised gives 96.7% precision.",
     "Positive Predictive Value (PPV).",
     "backend/data/ncfb_2026_cv_results.json",
     "Memorize 464 / 480 = 96.7%!"),

    (208, "How do you calculate recall from your confusion matrix?",
     "Recall = TP / (TP + FN) = 464 / (464 + 16) = 464 / 480 = 0.96666... = 96.67% (96.7%).",
     "464 criminals caught divided by 480 total real criminals in the dataset gives 96.7% recall.",
     "Sensitivity or True Positive Rate (TPR).",
     "backend/data/ncfb_2026_cv_results.json",
     "Shows balanced, symmetric performance."),

    (209, "How do you calculate F1 from precision and recall?",
     "F1 = 2 * (Precision * Recall) / (Precision + Recall) = 2 * (0.9667 * 0.9667) / (0.9667 + 0.9667) = 0.9667 (96.7%).",
     "Harmonic mean of two identical 96.7% scores equals 96.7%.",
     "Harmonic mean preserves balance.",
     "backend/data/ncfb_2026_cv_results.json",
     "Matches the 0.967 benchmark score."),

    (210, "Why is precision important in forensic investigations?",
     "Because police officers and cybercrime analysts have limited human resources. High precision (96.7%) guarantees that officers don't waste hundreds of hours chasing innocent citizens on false alarms.",
     "If the software rings 100 alarms a day and 90 are false, officers will mute the software. High precision ensures every alert is worth investigating.",
     "Minimizes Type I errors (False Positives) and alert fatigue.",
     "backend/app/main.py",
     "Alert fatigue is the number one reason police abandon analytics software."),

    (211, "Why is recall important?",
     "Because missing a kingpin or major terror financing wire transfer (False Negative) can have catastrophic national security consequences.",
     "If a terrorist moves money and the system misses it, people get hurt. Recall ensures nothing slips through.",
     "Minimizes Type II errors (False Negatives).",
     "backend/app/main.py",
     "High recall provides comprehensive investigative safety."),

    (212, "Which is more important: precision or recall in forensic anomaly detection?",
     "Precision is slightly more critical in initial screening to prevent alert fatigue and civil liberty violations, but in active terrorism or high-value kidnapping investigations, recall is prioritized to ensure zero missed targets.",
     "In daily screening, precision (don't waste police time). In a live kidnapping, recall (catch every clue).",
     "Threshold tuning: adjust contamination tau depending on investigative operational context.",
     "backend/app/main.py",
     "Shows you understand operational policing tradeoffs."),

    (213, "What does ROC-AUC 0.998 mean?",
     "It means there is a 99.8% probability that the model assigns a higher anomaly score to a randomly chosen criminal anomaly than to a randomly chosen innocent citizen transaction.",
     "Almost 100% confidence that real anomalies are scored as more suspicious than normal traffic.",
     "Near-perfect rank separation across score distributions.",
     "backend/data/ncfb_2026_cv_results.json",
     "Proves that our 5 features provide clean mathematical separation."),

    (214, "Are these real-world metrics?",
     "NO. These metrics were measured on our synthetic offline benchmark (NCFB-2026). Real-world production metrics will vary due to noisy sensor logs, telecom packet dropouts, and adversarial evasion tactics.",
     "No, this is our benchmark test score in the lab. On real city streets with messy data, scores will naturally be lower.",
     "Offline benchmark evaluation; real-world field performance requires continuous online calibration.",
     "backend/data/ncfb_2026_cv_results.json",
     "TRAP: Never promise 96.7% precision in real police production!"),

    (215, "Can you guarantee 96.7% in production?",
     "NO. Any engineer who guarantees 96.7% in production is bluffing. Production data suffers from non-stationary concept drift, incomplete CDRs, and sophisticated adversarial smurfing. We guarantee the mathematical reproducibility of 96.7% on our benchmark.",
     "No. No machine learning system can guarantee a fixed percentage in the real world because criminals constantly change their tricks.",
     "Concept drift and covariate shift prevent static accuracy guarantees in non-stationary real-world environments.",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Honesty here immediately earns the respect of senior interviewers."),

    (216, "Why 5-fold cross-validation?",
     "5-fold cross-validation provides an optimal 80/20 train/validation split across 10,000 records, ensuring each validation fold contains 2,000 records and exactly 96 anomalies, yielding low variance without excessive computational overhead.",
     "Testing the model on 5 different slices of the data so we know it didn't just get lucky on one test.",
     "Balances bias-variance tradeoff; K=5 is standard in ML benchmark literature.",
     "backend/scripts/run_offline_benchmark.py: line 45",
     "Standard scientific validation protocol."),

    (217, "What is StratifiedKFold?",
     "StratifiedKFold is a cross-validation splitting technique that ensures every fold contains the exact same percentage of target classes as the complete dataset (preserving the 4.8% anomaly ratio in all 5 folds).",
     "Making sure every slice of the cake gets the exact same percentage of criminal examples.",
     "Preserves class prior: P(y_val = -1) = P(y_global = -1) = 0.048 in each fold.",
     "backend/scripts/run_offline_benchmark.py: line 45",
     "Standard KFold can create folds with too few anomalies, distorting precision."),

    (218, "Why stratification?",
     "Because with imbalanced data (4.8% anomalies), random unstratified splitting could place 150 anomalies in Fold 1 and only 20 anomalies in Fold 2, causing massive statistical noise and unreliable metric estimates.",
     "To keep the test fair and consistent across all 5 slices.",
     "Eliminates sampling variance across folds.",
     "backend/scripts/run_offline_benchmark.py",
     "Mandatory for imbalanced classification benchmarks."),

    (219, "What happens in each fold?",
     "In each fold: 8,000 records form `X_train` and 2,000 records form `X_val`. RobustScaler fits on `X_train`. Isolation Forest fits unsupervised on `X_train`. Predictions are generated on `X_val`. Predictions are evaluated against held-out `y_val` to record TP, FP, FN, TN, and F1.",
     "Train on 8,000 rows without labels, test on 2,000 rows, compare against the hidden answer key, and repeat 5 times.",
     "Independent pipeline execution per fold with zero leakage.",
     "backend/scripts/run_offline_benchmark.py: lines 60-120",
     "Walk through this step-by-step."),

    (220, "What are your five F1 scores?",
     "Fold 1: 0.947, Fold 2: 0.958, Fold 3: 0.969, Fold 4: 0.979, and Fold 5: 0.974. Mean F1 = 0.9658 (~0.966), standard deviation sigma = ±0.0115.",
     "Scores range tightly between 94.7% and 97.9% across all 5 slices.",
     "Consistent fold metrics prove model stability across different data subsets.",
     "backend/data/ncfb_2026_cv_results.json",
     "Having the exact fold scores memorized shows you built it yourself."),

    (221, "What is your mean F1 and standard deviation?",
     "Mean F1 is 0.966 (96.6%) with a low standard deviation of sigma = ±0.0115 (1.15%), proving high stability across all partitions.",
     "Average score is 96.6%, with only 1% variation between slices.",
     "Low variance sigma = 0.0115 proves low estimator sensitivity to training samples.",
     "backend/data/ncfb_2026_cv_results.json",
     "High mean and low standard deviation indicate a robust model."),

    (222, "What is the generalization gap?",
     "The generalization gap is the absolute difference between average training F1 score and average validation F1 score: Gap = |Train_F1 - Val_F1|.",
     "The difference between practice test score and final exam score.",
     "Measures model over-fitting tendency.",
     "backend/data/ncfb_2026_cv_results.json",
     "Standard industry measure of model generalization."),

    (223, "How did you calculate the 0.2% gap?",
     "Across our 5 folds, average training F1 was 96.8% and average validation F1 was 96.6%: |0.968 - 0.966| = 0.002 = 0.2%.",
     "Practice score 96.8% minus real test score 96.6% equals 0.2%.",
     "Generalization Gap = |Train_F1 - Val_F1| = 0.002.",
     "backend/data/ncfb_2026_cv_results.json",
     "Well below the 3% industry threshold."),

    (224, "Does 0.2% prove no overfitting?",
     "YES. A small generalization gap (0.2% << 3.0%) proves that the model performs almost identically on unseen validation data as on training data, proving it learned true underlying geometric distributions rather than memorizing training samples.",
     "Yes, if the score hardly drops at all on new data, the model didn't memorize answers—it learned the real patterns.",
     "Mathematical proof of generalizable representation.",
     "backend/data/ncfb_2026_cv_results.json",
     "Disproves any claim that the model overfitted."),

    (225, "How do you detect underfitting?",
     "Underfitting occurs when both training F1 and validation F1 are low (e.g. Both around 60%), indicating that the model is too simple to capture the underlying structure. Our high 96.8% training F1 proves the model does not underfit.",
     "If you fail both practice tests and real tests, you underfit. Our model scores 96.8% on training, so it is not underfitting.",
     "High training bias indicates underfitting; our low training bias proves adequate capacity.",
     "backend/data/ncfb_2026_cv_results.json",
     "Shows full mastery of bias-variance tradeoff."),

    (226, "Why not 10-fold CV?",
     "10-fold CV increases training runtime by 2x while reducing the number of validation anomalies per fold to only 48, increasing statistical noise in fold precision estimates. 5-fold preserves 96 anomalies per fold, yielding more stable metric estimates.",
     "5 slices gave 96 criminals per test; 10 slices would cut it down to 48, making the percentages more jumpy.",
     "10-fold increases variance of the validation metric when sample counts in minority class are small.",
     "backend/scripts/run_offline_benchmark.py",
     "Justifies 5-fold with solid statistical reasoning."),

    (227, "THE MASTER TRAP: Isolation Forest is unsupervised, so where did labels come from?",
     "The ground-truth labels (`is_anomaly`) come from our synthetic benchmark generation script, which injected known forensic anomalies into the dataset. The labels were saved in the CSV file solely to serve as an evaluation oracle post-prediction.",
     "We created the test dataset with 480 known fake criminal transactions so we could grade the model's accuracy afterwards.",
     "Ground-truth vector y generated during synthetic data synthesis.",
     "backend/scripts/generate_synthetic_benchmark.py: lines 80-110",
     "Answer calmly and clearly: labels are synthetic ground truth."),

    (228, "Did the model train using the 480 anomaly labels?",
     "ABSOLUTELY NOT. During `.fit(X)`, the model is passed ONLY the feature matrix X. The `is_anomaly` column is stripped out before training. The model builds its trees completely blind to the labels.",
     "No, the model never saw the labels during training. The label column was completely removed before training started.",
     "Training call: `model.fit(X_train)` where X_train has shape (8000, 5) with zero label columns.",
     "backend/scripts/run_offline_benchmark.py: lines 75-90",
     "CRITICAL: Be firm and unambiguous on this point!"),

    (229, "If there are labels, why isn't this supervised learning?",
     "Because supervised learning uses labels in the loss function to guide gradient updates or split selections. In our pipeline, labels are NEVER used during tree construction; trees split on random features and random thresholds. Labels are only accessed post-prediction to grade the model.",
     "Supervised learning teaches the model with the answer key. We tested the model blind, and only used the answer key to calculate its grade.",
     "Loss function L(theta) has zero dependency on y during fitting.",
     "backend/scripts/run_offline_benchmark.py",
     "Shows deep conceptual clarity on machine learning paradigms."),

    (230, "How can you calculate F1 for an unsupervised model?",
     "By treating the evaluation as an external audit: the unsupervised model outputs discrete predictions (-1 or +1) purely through data geometry. We then compare those predictions against the benchmark's held-out ground-truth vector using standard classification metrics.",
     "The model makes its guesses with no help. Afterwards, we compare its guesses against the true list of anomalies to see how many it got right.",
     "External metric evaluation: `f1_score(y_true, y_pred)`.",
     "backend/scripts/run_offline_benchmark.py: line 115",
     "Completely standard in anomaly detection benchmarking."),

    (231, "What is an evaluation oracle?",
     "An evaluation oracle is an external, authoritative source of ground-truth truth used exclusively to assess the correctness of an algorithm's output without participating in the algorithm's internal decision logic.",
     "The teacher's answer key used strictly for grading after the exam papers are collected.",
     "External validation oracle in experimental computer science.",
     "backend/scripts/run_offline_benchmark.py",
     "Standard scientific terminology."),

    (232, "When are labels used in your code?",
     "Labels are accessed ONLY in lines 110-130 of `backend/scripts/run_offline_benchmark.py`, inside the `precision_score()`, `recall_score()`, and `confusion_matrix()` evaluation functions, long after `.fit(X)` and `.predict(X)` have completed.",
     "Only at the very end of the benchmark script when calculating the final score table.",
     "Confined strictly to evaluation metric calculation functions.",
     "backend/scripts/run_offline_benchmark.py: lines 110-130",
     "Open this file and show the line numbers if asked."),

    (233, "Does the model know which records are anomalies during training?",
     "No, zero knowledge. The model treats all 8,000 training rows as unlabelled data points in 5D space, isolating points purely based on density and coordinate distance.",
     "The model has zero idea which records are criminal and which are innocent while building its trees.",
     "Agnostic to target classes during tree construction.",
     "backend/app/main.py: line 2125",
     "Reinforces the unsupervised nature of the model."),

    (234, "Can an unsupervised model be evaluated using labeled data?",
     "YES. This is the universal standard in machine learning research (e.g. Evaluating K-Means clustering using Adjusted Rand Index against known labels, or evaluating Isolation Forest on benchmark datasets with known anomalies).",
     "Yes, all machine learning scientists test unsupervised models against labeled test data to prove they work.",
     "Standard practice in benchmark literature (ODDS, KDD-Cup, Kaggle anomaly detection).",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Quotes recognized scientific literature standards."),

    (235, "How is CrimeNet secured overall?",
     "Through 7 enterprise hardening controls: PBKDF2-HMAC-SHA256 password hashing (100k rounds), zero hardcoded secrets (.env vault), 15-minute JWTs with refresh token rotation, 4-tier RBAC, AES-256-GCM PII encryption, 30-day DPDP biometric purges, and SHA-256 Merkle tree evidence locking.",
     "Military-grade encryption for evidence, unhackable password storage, fast-expiring login tokens, and strict role permissions.",
     "Defense-in-depth security model across presentation, application, and persistence layers.",
     "backend/app/main.py: lines 180-280",
     "Covers credentials, data in transit, data at rest, and audit trails."),

    (236, "What is PBKDF2 and why use 100,000 iterations?",
     "PBKDF2 (Password-Based Key Derivation Function 2) applies pseudorandom HMAC-SHA256 repeatedly to stretch passwords. 100,000 iterations forces high computational cost, making GPU-accelerated dictionary attacks and rainbow-table precomputation mathematically infeasible.",
     "It scrambles passwords 100,000 times with random salt so hackers with supercomputers cannot crack them.",
     "DK = PBKDF2(HMAC-SHA256, Password, Salt, c=100000, dkLen=32). Recommended by OWASP and NIST.",
     "backend/app/main.py: lines 185-210",
     "Plain SHA-256 is vulnerable to GPU cracking; PBKDF2 forces deliberate computation delay."),

    (237, "Why use PBKDF2 over plain SHA-256?",
     "Plain SHA-256 is designed to be fast: an attacker with a modern GPU cluster can compute billions of SHA-256 hashes per second, cracking passwords via brute force. PBKDF2 introduces deliberate, tunable work factor delay (100k iterations).",
     "Plain SHA-256 is too fast, making it easy for hackers to guess passwords. PBKDF2 makes guessing passwords painfully slow.",
     "GPU cracking resistance: PBKDF2 forces sequential memory and CPU work.",
     "backend/app/main.py: lines 185-210",
     "Never use fast hashes (MD5, SHA-1, plain SHA-256) for password storage!"),

    (238, "What is AES-256-GCM and why GCM mode?",
     "AES-256-GCM (Galois/Counter Mode) is an Authenticated Encryption with Associated Data (AEAD) cipher. It encrypts suspect PII using 256-bit keys while generating a 128-bit authentication tag, guaranteeing both confidentiality and ciphertext tamper detection.",
     "It scrambles sensitive phone and bank numbers, and immediately detects if someone changed even one byte of the encrypted text.",
     "C, tag = AESGCM(key).encrypt(nonce, plaintext, associated_data). 96-bit unique nonces prevent replay.",
     "backend/app/main.py: lines 230-275",
     "ECB and CBC modes do not provide built-in ciphertext integrity; GCM does."),

    (239, "Why AES-256 over AES-128?",
     "AES-256 provides a 256-bit key space ($2^{256}$ combinations), providing post-quantum security margins against Grover's algorithm (which reduces symmetric key strength by half: 256 bits reduces to a secure 128 bits).",
     "256-bit keys are strong enough to resist future quantum computer attacks.",
     "Meets Top Secret military and intelligence compliance standards (CNSA suite).",
     "backend/app/main.py: line 235",
     "Shows forward-looking security design."),

    (240, "What is authentication in AES-GCM?",
     "Authentication in GCM means the cipher computes a GMAC (Galois Message Authentication Code) tag over the ciphertext and optional associated data. If an attacker tampers with even one bit of the encrypted ciphertext in SQLite, decryption fails with an `InvalidTag` exception.",
     "It is a tamper seal: if a hacker edits the encrypted text in the database, the decryption key refuses to open it.",
     "Prevents bit-flipping and chosen-ciphertext attacks.",
     "backend/app/main.py: line 250",
     "Guarantees data integrity alongside confidentiality."),

    (241, "What is JWT authentication?",
     "JWT (JSON Web Token) is a stateless, URL-safe compact security token comprising Header, Payload, and Signature, used to securely transmit cryptographically signed identity claims between client and server.",
     "A tamper-proof digital badge sent with every request that proves who you are and what role you have.",
     "Format: `base64(header).base64(payload).HMACSHA256(...)`.",
     "backend/app/main.py: lines 215-245",
     "Stateless; server does not need session storage in RAM."),

    (242, "What is a refresh token?",
     "A refresh token is a long-lived credential (e.g. 7 days) used strictly to request a new short-lived access token (15 minutes) without forcing the investigator to re-enter their password repeatedly.",
     "A renewal pass that lets your browser get a fresh 15-minute login pass without typing your password again.",
     "Stored securely in HttpOnly cookies or encrypted storage.",
     "backend/app/main.py: lines 220-250",
     "Limits exposure if an access token is intercepted."),

    (243, "Why rotate refresh tokens?",
     "Refresh token rotation guarantees that whenever a refresh token is used, it is invalidated and replaced with a new one. If an attacker steals a refresh token and tries to use it, the server detects reuse, invalidates the entire token family, and terminates the session.",
     "Every time you use a renewal pass, it is destroyed and replaced. If a thief tries to reuse an old pass, the alarm trips and logs everyone out.",
     "Prevents persistent session hijacking and token replay attacks.",
     "backend/app/main.py: lines 225-255",
     "OAuth2 Best Current Practice (BCP) compliance."),

    (244, "What is RBAC and why use it?",
     "Role-Based Access Control restricts system functionality and data visibility based on user roles, preventing unauthorized personnel from accessing wiretaps, modifying evidence, or viewing sensitive informant names.",
     "Ensuring junior officers can only view public case summaries, while only lead detectives can see wiretaps and confirm evidence.",
     "Enforces principle of least privilege.",
     "backend/app/main.py: lines 240-270",
     "Prevents horizontal and vertical privilege escalation."),

    (245, "What are your four access levels?",
     "(1) `admin` (system config, user provisioning, audit inspection); (2) `lead_investigator` (full review, case confirmation, warrant export); (3) `analyst` (graph link traversal, alert reviews); and (4) `officer` (read-only view of confirmed dossiers).",
     "Admin, Lead Detective, Intelligence Analyst, and Patrol Officer.",
     "Hierarchical role set enforced via FastAPI dependencies.",
     "backend/app/main.py: line 245",
     "Know all 4 roles and their exact permissions."),

    (246, "What happens if a token is stolen?",
     "The stolen access token expires automatically within 15 minutes. If the attacker attempts to use the stolen refresh token, token rotation detects duplicate token usage, immediately revokes all tokens for that user, and alerts the security audit log.",
     "The stolen token stops working in 15 minutes. If the hacker tries to renew it, the system detects the theft and blocks the account.",
     "Automatic token family revocation.",
     "backend/app/main.py",
     "Limits breach blast radius."),

    (247, "How do you protect passwords?",
     "Passwords are never stored in plaintext. They are salted with 16 random cryptographically secure bytes (`os.urandom(16)`) and hashed using PBKDF2-HMAC-SHA256 with 100,000 iterations before being stored in SQLite.",
     "We add random salt and scramble the password 100,000 times before saving it to disk.",
     "Hash format: `pbkdf2:sha256:100000$salt$hash`.",
     "backend/app/main.py: lines 185-210",
     "Never store passwords in plain text!"),

    (248, "How do you protect sensitive evidence?",
     "Sensitive evidence PII (phone numbers, bank account numbers, suspect names) is encrypted at rest using AES-256-GCM, hashed into SHA-256 Merkle trees for integrity verification, and accessed strictly through RBAC-authorized APIs.",
     "Military-grade encryption on the database file, tamper seals on every evidence row, and strict badge login.",
     "Confidentiality: AES-256-GCM; Integrity: SHA-256 Merkle tree; Access: RBAC.",
     "backend/app/main.py: lines 230-280",
     "Comprehensive defense-in-depth."),

    (249, "How do you protect APIs from unauthorized access?",
     "All analytical APIs require an `Authorization: Bearer <token>` header, validated on every request via FastAPI's security dependency `Depends(require_auth)`. Unauthenticated requests immediately receive HTTP 401 Unauthorized.",
     "Every single API call must show a valid digital badge, or the server rejects it instantly.",
     "FastAPI security middleware with JWT cryptographic signature verification.",
     "backend/app/main.py: lines 235-265",
     "No open, unprotected endpoints exist."),

    (250, "How do you prevent unauthorized database access?",
     "The SQLite file is stored with restricted OS filesystem permissions (0600: read/write only by the backend service user), sensitive columns are encrypted with AES-256-GCM, and the database file is never exposed to public internet ports.",
     "The database file is locked to the operating system user, sensitive columns are encrypted, and no database ports are open to the internet.",
     "Least-privilege filesystem ACLs + Column-level encryption + Zero listening socket ports.",
     "backend/crimenet.db",
     "SQLite has no open network listening socket, making remote SQL injection via port attacks impossible."),

    (251, "How would you perform security testing?",
     "By executing automated SAST (Static Application Security Testing) using Bandit for Python, DAST (Dynamic Application Security Testing) using OWASP ZAP against REST endpoints, penetration testing for JWT tampering, and SQL injection fuzzing.",
     "Run automated vulnerability scanners, test for fake JWT tokens, and try to break into the API with hacker tools.",
     "Bandit + OWASP ZAP + PyTest security assertion suites.",
     "backend/tests/test_responsible_ai.py",
     "Demonstrates professional DevSecOps understanding."),

    (252, "Why use SHA-256 for evidence hashing?",
     "SHA-256 is an NIST-approved, collision-resistant cryptographic hash function that produces a unique 64-character hexadecimal fingerprint. Finding two different evidence logs that produce the same SHA-256 hash requires $2^{128}$ operations, which is computationally impossible with existing human supercomputers.",
     "It is a digital fingerprint that cannot be faked or duplicated by any supercomputer on Earth.",
     "Cryptographic collision resistance under FIPS 180-4 standard.",
     "backend/app/main.py: lines 3240-3270",
     "The industry benchmark for digital forensics."),

    (253, "What is a cryptographic hash?",
     "A cryptographic hash is a one-way deterministic mathematical algorithm that converts arbitrary-sized input data into a fixed-size bit string, such that it is computationally infeasible to invert (find the original text) or find collisions (two inputs with same output).",
     "A one-way meat grinder: easy to turn steak into ground meat, impossible to turn ground meat back into steak.",
     "One-way function f: {0,1}* -> {0,1}^256 with preimage and second-preimage resistance.",
     "backend/app/main.py",
     "Hashes are one-way; encryption is two-way."),

    (254, "What happens if one byte of evidence changes?",
     "Due to the cryptographic avalanche effect, modifying a single byte in an evidence log causes over 50% of the bits in the calculated SHA-256 hash to change completely and unpredictably, immediately invalidating the Merkle Root Hash.",
     "Change one letter in a 1,000-page file, and the entire digital fingerprint changes completely, sounding the alarm.",
     "Strict avalanche criterion: bit independence in SHA-256 compression rounds.",
     "backend/app/main.py: lines 3240-3320",
     "Instantly proves evidence tampering."),

    (255, "What is a Merkle tree?",
     "A Merkle tree is a hierarchical binary cryptographic hash tree where raw evidence items reside at the leaf nodes, and internal nodes contain the hash of their concatenated children, culminating in a single Merkle Root Hash.",
     "A pyramid of digital fingerprints where every pair of files is hashed together until you get one master fingerprint at the peak.",
     "Binary tree of hashes invented by Ralph Merkle (1979).",
     "backend/app/main.py: lines 3240-3320",
     "Allows proving integrity of any individual file in O(log N) operations."),

    (256, "How does a Merkle tree work step by step?",
     r"1. Canonicalize evidence strings. 2. Compute leaf hashes: $H_A = \text{SHA256}(\text{Item}_A)$. 3. Pair adjacent leaves: $H_{AB} = \text{SHA256}(H_A \parallel H_B)$. 4. Recurse up tree levels. 5. If odd number of nodes, duplicate last node. 6. Output single 64-character Merkle Root Hash.",
     "Hash each file -> Hash pairs of hashes -> Keep pairing up until you reach the single master root hash.",
     "Binary reduction: N leaves reduce to 1 root in ceil(log2 N) levels.",
     "backend/app/main.py: lines 3250-3290",
     "Walk through these 6 steps on the whiteboard."),

    (257, "Why use a Merkle tree over a single flat hash?",
     r"A single flat hash over 10,000 evidence items requires re-hashing all 10,000 files to verify a single document ($O(N)$). A Merkle tree allows verifying a single evidence item in $O(\log N)$ operations using a compact audit path, without revealing the rest of the confidential case file.",
     "With a flat hash, proving one receipt requires showing all 10,000 confidential files. With a Merkle tree, you can prove that one receipt with just 14 hashes without exposing other suspects' files.",
     "Logarithmic verification complexity: O(log2 N) vs O(N); enables selective redaction for court disclosure.",
     "backend/app/main.py: lines 3280-3320",
     "Allows selective disclosure in court!"),

    (258, "What is a root hash?",
     "The Merkle Root Hash is the single 256-bit cryptographic digest at the top of the Merkle tree that represents the immutable state of all evidence items in the tree.",
     "The master digital seal at the top of the pyramid that protects all the files underneath.",
     "Root vertex H_root in {0,1}^256.",
     "backend/app/main.py: line 3260",
     "This is the hash stamped on Section 63 BSA certificates."),

    (259, "What is a leaf hash?",
     "A leaf hash is the cryptographic SHA-256 digest computed directly from a single canonicalized raw evidence record (e.g. A single CDR phone call record or toll camera photo).",
     "The digital fingerprint of one single piece of evidence at the bottom of the tree.",
     "H_leaf = SHA256(canonical_evidence_string).",
     "backend/app/main.py: line 3250",
     "Bottom layer of the tree."),

    (260, "How do you construct a leaf hash in CrimeNet?",
     "We canonicalize the evidence dictionary into a deterministic sorted JSON string with stripped whitespace, and hash the UTF-8 bytes using SHA-256: `SHA256(json.dumps(record, sort_keys=True).encode('utf-8'))`.",
     "Sort the record keys alphabetically, turn it into text, and take its SHA-256 fingerprint.",
     "Deterministic canonical serialization prevents key-ordering mismatch bugs.",
     "backend/app/main.py: lines 3245-3255",
     "Without canonical sorting, identical records produce different hashes!"),

    (261, "How do you verify evidence integrity?",
     r"An auditor takes the suspect evidence item, computes its leaf hash, retrieves the $O(\log N)$ sibling hashes (the Merkle audit path), hashes up to the root, and checks if the calculated root matches the published sealed root hash.",
     "Hash the target file, follow the 14-step ladder of companion hashes to the top, and see if it matches the master seal.",
     "Matches calculated H_root against signed certificate root.",
     "backend/app/main.py: lines 3290-3320",
     "Runs in sub-millisecond time."),

    (262, "Can a Merkle tree prove authenticity?",
     "NO. A Merkle tree proves technical data integrity (that the data was not altered post-ingestion). It does NOT prove authenticity (whether the person named on the invoice actually wrote it or if the log was fabricated before entering the database).",
     "It proves no one edited the file after it was saved. It doesn't prove the file was truthful when it was created.",
     "Integrity != Authenticity. Authenticity requires witness testimony and digital signatures.",
     "backend/app/main.py",
     "CRITICAL TRAP: Integrity proves absence of tampering, not truthfulness!"),

    (263, "Can it prove lawful collection?",
     "NO. A cryptographic hash tree cannot verify whether police obtained a legal Section 5(2) search warrant before wiretapping the suspect. If police conducted an illegal warrantless wiretap, hashing it into a Merkle tree does NOT make it lawful!",
     "A wax seal cannot prove that the police had a legal search warrant when they seized the letter.",
     "Lawfulness of seizure is a constitutional judicial question, not a cryptographic hash function.",
     "backend/app/main.py",
     "Never claim cryptography replaces a search warrant!"),

    (264, "Can it prove chain of custody?",
     "It proves technical electronic chain of custody (that the electronic bytes remained untampered while in custody), but physical chain of custody (who carried the hard drive, evidence locker logs) requires signed procedural documentation.",
     "It proves the digital bytes never changed, but officers must still sign paper locker receipts.",
     "Digital integrity is one half of chain of custody; physical custody is the other half.",
     "backend/app/main.py",
     "Both physical and digital chains of custody are required in court."),

    (265, "Does it automatically make evidence admissible?",
     "NO. Admissibility under Section 63 BSA 2023 is decided exclusively by the presiding judge, who evaluates search warrant legality, relevancy, procedural compliance, and witness credibility. The Merkle tree satisfies the technical integrity requirement, not the judicial decision.",
     "No software can decide what is admissible; only the judge in the courtroom has the power to admit evidence.",
     "Judicial discretion under Section 63 BSA 2023.",
     "backend/app/main.py",
     "Never claim an algorithm makes evidence automatically admissible!"),

    (266, "What does your Section 63 BSA claim actually mean?",
     "It means CrimeNet AI provides the technical certifications required under Section 63(4) of Bharatiya Sakshya Adhiniyam (BSA) 2023: certifying the device operated properly, data was hashed with SHA-256 upon ingestion, and cryptographic root hashes verify zero post-ingestion tampering.",
     "It means our software prints the official technical certificate proving the electronic records were kept safely without tampering.",
     "Generates electronic certificate compliant with Section 63(4) BSA 2023.",
     "backend/app/main.py: lines 3250-3310",
     "Citing Section 63(4) shows deep statutory precision."),

    (267, "Is CrimeNet legally certified?",
     "No. CrimeNet AI is a technical prototype developed for academic research and hackathon defense. Formal certification for Indian law enforcement requires testing by CFSL (Central Forensic Science Laboratory) and MeitY accreditation.",
     "It is a research prototype; official court certification requires formal government lab audits.",
     "Adheres to technical requirements of Section 63 BSA, but is not yet formally certified by CFSL.",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Always be honest about prototype status."),

    (268, "Is CrimeNet court-approved?",
     "No. Indian courts do not 'pre-approve' software. Software evidence is admitted on a case-by-case basis through Section 63 BSA certificates and expert witness testimony under Section 39 BSA (formerly Section 45 Evidence Act).",
     "Courts don't approve software brands; they examine the electronic certificate in each individual trial.",
     "Case-by-case evidentiary admissibility under judicial review.",
     "c:/Users/Aditya/Downloads/SIH 2026",
     "Explains how Indian evidence law actually works in trial courts."),

    (269, "Does CrimeNet determine guilt?",
     "ABSOLUTELY NOT. CrimeNet AI is an investigative decision-support platform. Determining criminal guilt is the exclusive constitutional prerogative of a trial court judge after considering all oral, documentary, and forensic evidence beyond reasonable doubt.",
     "No, the software never determines guilt. Only a judge in court can declare someone guilty.",
     "Presumption of innocence under Indian jurisprudence (Article 21).",
     "backend/tests/test_responsible_ai.py",
     "CRITICAL TRAP: Never say the AI proves guilt!"),

    (270, "Can CrimeNet arrest someone?",
     "NO. CrimeNet has zero physical or autonomous capability. Arrest is an executive police power governed by Section 41 CrPC / Section 35 BNSS 2023, requiring a police officer's lawful authority and judicial arrest warrants.",
     "No, software cannot arrest anyone. An authorized police officer must carry out arrests under legal warrant.",
     "Executive statutory authority strictly reserved for human police officers.",
     "backend/tests/test_responsible_ai.py",
     "Zero autonomous enforcement."),

    (271, "Can CrimeNet issue warrants?",
     "NO. Warrants under Indian criminal law (Section 70 CrPC / Section 72 BNSS 2023) can ONLY be issued by a Judicial Magistrate or competent court of law, signed and sealed by the judge.",
     "No, only a real judge sitting in a courtroom can issue a legal warrant.",
     "Judicial power; software has zero authority to issue warrants.",
     "backend/tests/test_responsible_ai.py",
     "CrimeNet generates draft case files for an officer to present to a judge."),

    (272, "Can CrimeNet freeze accounts?",
     "NO. Freezing bank accounts is a statutory police power under Section 102 CrPC / Section 106 BNSS 2023, requiring written orders from a police officer and immediate reporting to the Judicial Magistrate.",
     "No, only a police superintendent with court reporting can freeze bank accounts.",
     "Statutory police power under Section 102 CrPC / Section 106 BNSS.",
     "backend/tests/test_responsible_ai.py",
     "CrimeNet provides advisory alerts; human officers execute legal orders."),

    (273, "What is the role of the investigator?",
     "The investigator is the sole decision-maker: reviewing advisory alerts, examining Explainable AI baselines, verifying physical alibis, interviewing witnesses, securing search warrants, and making all enforcement decisions.",
     "The human detective is the captain; CrimeNet is just the radar screen on the ship.",
     "Human-in-the-Loop primary decision agent.",
     "backend/tests/test_responsible_ai.py",
     "Emphasizes that AI is a tool, not a replacement."),

    (274, "What legal limitations does your prototype have?",
     "Three legal limitations: (1) Prototype status (not audited by CFSL); (2) Evaluated on synthetic data (not validated on live citizen wiretaps); (3) Merkle tree establishes technical data integrity post-ingestion, not search warrant legality.",
     "It is a research prototype tested on synthetic data, and its hashes prove file safety, not search warrant legality.",
     "Statutory and operational boundaries clearly declared.",
     "backend/app/main.py",
     "Panels respect clear acknowledgment of legal boundaries."),

    (275, "What does Section 63 BSA mean for digital evidence?",
     "It sets the statutory conditions for admissibility of electronic records: requiring evidence that the computer was operating properly, records were produced in the ordinary course of business, and an authorized officer signs a certificate verifying integrity.",
     "The law that requires computer evidence to come with a signed technical certificate proving zero tampering.",
     "Substantive compliance with Section 63(1) through 63(4) of Bharatiya Sakshya Adhiniyam 2023.",
     "backend/app/main.py: lines 3250-3300",
     "The legal foundation of electronic evidence in India.")
]

print(f"Loaded {len(BATCH3_QUESTIONS)} questions in Batch 3.")
